### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by fatagun** [getsentry/raven-csharp#107]
Hello,

Is Raven C# client thread safe?

Can I have a single instance per application? or instance per request?

What is the best practice?

Thanks.

**Comment by asbjornu** [comment]
@fatagun Hi. To be safe, I'd instantiate `RavenClient` for each thread. Although the `Capture` methods don't mutate state and create new `HttpWebRequest` objects per invocation, there are other properties and such on `RavenClient` that might not be thread safe, so to be sure, I'd create one client per thread.

**Comment by fatagun** [comment]
ok thank you.
