### ISSUE TITLE
Exception.Data in RavenSharp 1.5.1 ?

### ISSUE THREAD

**Issue by LordMike** [getsentry/raven-csharp#108]
Is `Exception.Data` included in `RavenSharp 1.5.1`?
I'm trying out stuff like:

    ex.Data.Add("Hello world", "Hello");
    ravenClient.CaptureException(ex);

But I'm not seeing the "Hello world" in Sentry. I also can't find it in the actual submission to Sentry (as seen with Fiddler), so I suspect it's never sent. Is #87 not in 1.5.1 ?

**Comment by asbjornu** [comment]
@LordMike No, `Exception.Data` is only available in [2.0 (unstable)](https://www.nuget.org/packages/SharpRaven/2.0.0-unstable0209). I'm hoping to get a stable release out this week.

**Comment by LordMike** [comment]
Awesome. :+1: 
I went ahead and used the dictionary anyways - it'll all sort itself in 2.0+ then.

**Comment by razzmatazz** [comment]
New version would be nice. I've been waiting for a fix to #101 for two months already :)

Thanks

**Comment by asbjornu** [comment]
@razzmatazz [2.0](https://www.nuget.org/packages/SharpRaven/2.0.0) was published just a few hours ago. Get it while it's hot! :fire: :smile:
