### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by GotenXiao** [getsentry/raven-csharp#110]
Congratulations on the release of 2.0!

Unfortunately, the documentation is still showing for the 1.x API (both on the GitHub README and on https://docs.getsentry.com/hosted/clients/csharp/). This caused some confusion when installing SharpRaven on a new project and being told that CaptureException was deprecated.

**Comment by asbjornu** [comment]
@GotenXiao Thanks for pointing this out. I'll be sure to get to it some day, but if you have time to fix it, I would highly appreciate a pull request. You can edit the documentation directly on GitHub, no need to fork or clone locally. Just browse to the file you want to edit and click the edit pencil.

**Comment by c0bra** [comment]
:+1:

**Comment by c0bra** [comment]
@asbjornu Furthermore, while `CaptureException(Exception)` is deprecated it's still in use in the units tests...: https://github.com/getsentry/raven-csharp/blob/master/src/tests/SharpRaven.UnitTests/RavenClientTests/CaptureExceptionTests%20.cs

How are we SUPPOSED to capture an Exception? With `CaptureException(new SentryEvent(Exception))`?

I'd be happy to update the docs (or add an implicit operator) if you can give some direction.

**Comment by asbjornu** [comment]
@c0bra The unit tests will continue to execute methods that exist until they are removed, to ensure that they still work, although deprecated. The recommended way to capture exceptions now is with the [`Capture(SentryEvent)`](https://github.com/getsentry/raven-csharp/blob/develop/src/app/SharpRaven/IRavenClient.cs#L97) and [`CaptureAsync(SentryEvent)`](https://github.com/getsentry/raven-csharp/blob/develop/src/app/SharpRaven/IRavenClient.cs#L161) methods. All other `Capture...()` methods are `[Obsolete]` as you can see.
