### ISSUE TITLE
Ability to set the SentryUser via the SentryEvent interface?

### ISSUE THREAD

**Issue by ryankanno** [getsentry/raven-csharp#113]
I don't see a clean way to access the properties of the SentryUser via the new SentryEvent Capture interface. 

Currently, I'm setting some tags to be able to filter the user, but would like to access the SentryUser to be able to set the fields programmatically.

**Comment by asbjornu** [comment]
@ryankanno Thanks for reporting this. I've released a [2.1 prerelease on NuGet](https://www.nuget.org/packages/SharpRaven/2.1.0-unstable0020) that I would very much appreciate if you could test and report back whether fixes the problem or not.

**Comment by lwhuybrechts** [comment]
@ryankanno We've also experienced this problem. The way we fixed it is to inject a custom SentryUserFactory in the RavenClient, in which we override the OnCreate function. Here we set the properties of the user.

**Comment by ryankanno** [comment]
@lwhuybrechts I did look at https://github.com/getsentry/raven-csharp/blob/develop/src/app/SharpRaven/RavenClient.cs#L288 to do that, but in my case, I wanted to dynamically set properties based on constructs that weren't in a global scope. I could have it injected it somewhere where it was accessible, but it felt a bit like I was fighting the lib. :)

**Comment by asbjornu** [comment]
@ryankanno If you have ideas on how it could be done more elegantly, please write them here or submit a pull request. I don't have time to look into this myself in a while, I'm afraid.

**Comment by ryankanno** [comment]
@asbjornu I could take a stab at it. Is there any historical context as to why it wasn't exposed on the SentryEvent interface? (Only so that I don't go down routes that weren't expected). At first glance, it seems like the resulting JsonPacket could just absorb the User from the SentryEvent interface (if it were exposed).

**Comment by asbjornu** [comment]
@ryankanno There's no particular reason I can think of, so please add it the way you think is best and do a PR in which we can discuss the details. :+1:

**Comment by asbjornu** [comment]
Closing this in await for a pull request.

**Comment by rolandh** [comment]
Did anyone attempt a pull request? I might do so if no one has.
