### ISSUE TITLE
Error Level not working (SharpRaven.2.1.0-unstable0020)

### ISSUE THREAD

**Issue by hmiguel** [getsentry/raven-csharp#119]
Hey,

I'm testing the realease **2.1.0-unstable0020** and I can't set the **Error Level** status, always return "Error" status.

`(...)
@event.Level = ErrorLevel.Debug;
 raven.Capture(@event);`

Even with the old api!

` raven.CaptureMessage(msg, ErrorLevel.Debug);`

Thanks

**Comment by tonymke** [comment]
We are also experiencing this on the current stable release on NuGet.

Consider this simple example program:

```
            var client = new RavenClient("OMITTED");
            var ev = new SentryEvent("TEST INFO EVENT");
            ev.Level = ErrorLevel.Info;
            client.Capture(ev);            
```

The event is logged as an error, irrespective of the fact we specified the event as Informative, it is logged as an error on GetSentry, as shown in this screenshot: http://i.imgur.com/bwOpGRg.png

**Comment by Jakehp** [comment]
I'm experiencing the same issue as well. +1

**Comment by asbjornu** [comment]
As you can see by the Release Note, this was fixed in [version 2.1.0-unstable0025](https://www.nuget.org/packages/SharpRaven/2.1.0-unstable0025):

> Fixes for HttpContext and missing log level when capturing the new SentryEvent class.

I would therefore recommend upgrading to [version 2.1.0-unstable0028](https://www.nuget.org/packages/SharpRaven/2.1.0-unstable0028) and testing again. I'm pretty certain that should fix this and a few other problems.

**Comment by asbjornu** [comment]
If you can confirm this fix, I'll release a stable version 2.1 of this later today.

**Comment by hmiguel** [comment]
@asbjornu It seens ok. Thanks.

**Comment by asbjornu** [comment]
@hmiguel Thanks for testing. A stable [version 2.1](../releases/tag/2.1) is now out.

**Comment by Jakehp** [comment]
Thanks @asbjornu :+1:
