### ISSUE TITLE
PCL support?

### ISSUE THREAD

**Issue by mogikanin** [getsentry/raven-csharp#126]
Do you have plans to ship assemblies for .net portable too?

**Comment by asbjornu** [comment]
@mogikanin I know nothing about PCL, but would be happy to accept pull requests for it!

**Comment by mogikanin** [comment]
In current state it's not easy to build PCL version since StackTrace\StackFrame types are not included into PCL. But luckily at the moment I need only version for Xamarin.Mac (targetFramework="xamarinmac20"), and I tried to build it, and it works fine :) Just tested it with my Xamarin.Mac application. Here my [fork](https://github.com/mogikanin/raven-csharp/tree/xamarin.mac) with changes. If you want, I can sent it as pull request.

**Comment by asbjornu** [comment]
@mogikanin If you could submit a PR with your rebased changes, it would be easier to compare, so yes; please do so! :smiley:

**Comment by mogikanin** [comment]
Ok, I've submitted PR.

**Comment by asbjornu** [comment]
@mogikanin Excellent. Let's continue the discussion in #145 and close this?

**Comment by Dids** [comment]
Any news on the PCL side of things?

**Comment by asbjornu** [comment]
@Dids: We warmly welcome help with getting #145 to pass the test suite.
