### ISSUE TITLE
Send to analysis a text long (log) to Sentry (Initial version with send for Microsoft Storage)

### ISSUE THREAD

**Issue by samukce** [getsentry/raven-csharp#127]
Hi guys!

We have decided to use to getsentry to capture errors and information. So, in specials situations, i had that capture a long text to analyse sent from desktop applications.

The better solution was to send the file to Microsoft Storage and in the extra message of the Sentry put the link to access the file.

Maybe someone has a similar situation. Then I put in NuGet and Github.

Source: https://github.com/samukce/raven-csharp-extra-cloudstorage
https://www.nuget.org/packages/SharpRaven.ToStorage/

**Comment by dcramer** [comment]
What kind of text is it? Curious what might be useful that we don't yet support today. 

Closing this ticket out but let's keep convo going.

**Comment by samukce** [comment]
For instance, when is a system of communication with another system and then, for understand exactly what happened in some error situation is useful to read all communication until that moment. No is necessarily a stacktrace, but a communication log.
This way is it possible capture a logtext of business without human interaction.

**Comment by asbjornu** [comment]
@samukce It sounds like [Breadcrumbs](https://docs.getsentry.com/hosted/learn/breadcrumbs/) might be a better solution to this problem. Have you looked at it? It's currently not supported in the SharpRaven client, but if you find that this is a feature that perhaps solves your use-case better, I'm happy to receive a pull request for it. :smile:

**Comment by samukce** [comment]
".. whenever an error or other Sentry event is submitted to the system, breadcrumbs that were logged before are sent along to make it easier to reproduce what lead up to an error."

I think so! =D
I will be happy to contribute.
