### ISSUE TITLE
RateLimit

### ISSUE THREAD

**Issue by tigerclawn82** [getsentry/raven-csharp#129]
Hi, is there any Plan to support rate limiting?

**Comment by asbjornu** [comment]
@tigerclawn82 Is this supported in any of the other Sentry clients? How would it work?

**Comment by dcramer** [comment]
@asbjornu we do support the rate limited response in at least a couple clients for back off timers. It's implemented as the standard 429 header with a retry-after header in most cases.

**Comment by asbjornu** [comment]
I see. A pull request for this would be highly appreciated, @tigerclawn82.

**Comment by bruno-garcia** [comment]
We've released the new SDK which solves this issue:

https://github.com/getsentry/sentry-dotnet/releases

https://www.nuget.org/packages/Sentry

I'll close this issue but please feel free to reopen or open one in the new repository if you have any issues integrating. We'll be happy to help you moving over to the new SDK.
