### ISSUE TITLE
Exception thrown in Capture for an exception

### ISSUE THREAD

**Issue by LordMike** [getsentry/raven-csharp#144]
So, slight issue here (unsure what's wrong). When calling Capture on a `SentryEvent` created from an exception I'd like to track, I get an `ArgumentNullException`. Apparently an enum is being parsed, but `TryParseEnum` barfs on it. The entire stack trace (all one lines of it) are below. In the image further down, you can see the creation of the `SentryEvent`.

     at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)

![image](https://cloud.githubusercontent.com/assets/1027111/17839929/67ecd510-67f8-11e6-9616-532b71ebf590.png)

The RavenSharp project doesn't seem to call TryParseEnum itself, so I'm wondering where it comes from?

I'll try using the ravensharp source to dig deeper.

**Comment by LordMike** [comment]
Apparently it happens in `SharpRaven.Data.Requester::Request()`. I am unsure what exactly is null - and as the event doesn't end in my sentry, it may be that the request never leaves the client.When I went to investigate by running Fiddler to capture the events, I suddenly got an exception on the `return response.id;` line - I unfortunately missed the text as I clicked F5 too quickly.

That event (no. 2 in this text) did however end up in Sentry. The third and fourth runs of the code gave no exceptions at all (In SharpRaven), and landed in Sentry also.

![image](https://cloud.githubusercontent.com/assets/1027111/17839994/29e22b92-67fa-11e6-97c1-3882187098c5.png)

Fluke?

**Comment by asbjornu** [comment]
@LordMike Thanks for digging into this! Not sure what's going on there, but that code could indeed use some more error recovery, checks and bounds. Since you already have your nose deep into this code, would you care to create a pull request improving it? :smiley:

**Comment by LordMike** [comment]
I have no idea what's wrong.. It seems like some internal thing in .NET itself, which makes it very hard.
I had a number of other weird issues yesterday too, so I'll try again today and see if they're reproducible.

**Comment by asbjornu** [comment]
@LordMike The return of `response.id` without checkout `response != null` is asking for trouble. The same is casting `webRequest.GetResponse()` to `HttpWebResponse` without a null-check first. `webRequest.GetResponse() as HttpWebResponse` would have been more robust, but a `null`-check there would be good regardless.

**Comment by LordMike** [comment]
Ah, that part. I figured out the errors though.

A colleague pointed out that my stack was all crazy when VS gave me the exception (not the stacktrace, but the Stack view in VS) - I was way inside mscorlib. Apparently, I had `Just My Code` disabled under debugging options. This makes VS try to debug anything an all, and not just my own code (hence the name)..

I suspect this option was disabled under a run of Release code, where VS will popup a window with 4 options. Clicking wrong here can apparently lead to disastrous consequences.

Re-enabling `Just My Code` will suddenly render my code usable, and I couldn't reproduce anymore.. This is insane. Don't touch that button, kids!

**Comment by asbjornu** [comment]
@LordMike I'm glad you figured it out! :smile:
