### ISSUE TITLE
Ideas on demangling the function names of async tasks?

### ISSUE THREAD

**Issue by marcomorain** [getsentry/raven-csharp#147]
Hi there,

I'm currently trying to clean up how our C# stack-traces look in Sentry. You merged my PR last week to add the 'in-app' flag which has made a _huge_ difference. Now we only see our code by default in stack traces.

The next piece I want to try to tackle is the names of async functions, but I thought it best to open an issue before writing any code.

Our stack-traces (from the dotnet runtime) have items that look like this: (and they appear the same in Sentry:)

`Flipdish.Web.Controllers.PollApiController+<RequestNewOrders>d__4 in MoveNext at line 37:13`

Which comes from this code:

```C#
public async Task<ActionResult> RequestNewOrders()
{
  var requestTime = System.Web.HttpContext.Current.Timestamp;
  var userId = User.Identity.GetUserId<int>();
  // The following is line 37, which is 'MoveNext' I guess:
  IEnumerable<PreviousOrderDm> result = await _posApiService.RequestNewOrders(requestTime, userId); 
// ...
}

```

At first glance, it looks like the C# compiler is creating a little function with a random name in place of the `async`/`await` syntactic sugar, which results in the method name `PollApiController+<RequestNewOrders>d__4 in MoveNext`.

I wonder is there a way to get a nicer looking name than that?

In the past I have worked on Clojure projects and run into the same problem. The Clojure compiler creates JVM function with similar names; Clojure functions can have characters in the function name that the JVM does not allow, such as `?` and `!`. The Clojure compiler will replace these characters with `_QMARK_` and `_BANG`. A function named `list?` in Clojure will be named `list_QMARK_` when compiled for the JVM. Clojure exception loggers will typically have a demangling step which will reverse these replacements in the function names, so that the function name reported to Sentry, for example, would be `list?`. The happens in the exception logging client before the JSON is sent to the logger.

Here is such a look-up table.

https://github.com/mmcgrana/clj-stacktrace/blob/master/src/clj_stacktrace/core.clj#L22-L34

I wonder if it would be possible to do the same in raven-csharp?

We might be able to change:

`Flipdish.Web.Controllers.PollApiController+<RequestNewOrders>d__4 in MoveNext at line 37:13`

to:

`Flipdish.Web.Controllers.PollApiController.RequestNewOrders in async task at line 37:13`

What do you think? Good idea/crazy idea?

**Comment by marcomorain** [comment]
Screenshot of what it looks like in Sentry:

![mangle](https://cloud.githubusercontent.com/assets/448001/17928488/c6178418-69f2-11e6-95ba-c930dfd7802b.png)

**Comment by asbjornu** [comment]
@marcomorain I've seen the problem and think this is a good idea. The problem is that we can't know beforehand what scheme the compiler will use when translating lambdas, `async` and other syntactic sugar constructs to MSIL. In the future, we most likely only have to care for what Roslyn does, but today we at least need to cater for `cs.exe` and [`dmcs`](http://www.mono-project.com/docs/about-mono/languages/csharp/) (I think we can ignore `smcs` and `gmcs`). Thoughts?

**Comment by marcomorain** [comment]
Brain dump on the train:

I was going to try out an approach of progressive enhancement - if we can pattern match against some known constructs, we could improve any levels of the callstack that match, leaving anything that doesn't match as-is. 

This would mean that users of compilers that we have not added support for get the same sentry experience that we have now, whereas users on known compilers could end up with a richer callstack. 

I'm hoping that this would mean that we could add patterns to recognise over time (and keep up to date with new compilers). 


In terms of recognisers, I was thinking that if a stack frame module matches something like <`identifier`>D__`x` (Where identifier is some C# identifier and x is a digit), and the function is called MoveNext then we should be able to change the reported function name to "await async task". 

We would need a set of huerustics that match all of the compilers that we want to support, like you said. The heuristics would perhaps be a set of predicate that recognises patters mapping to a set of functions from stack frame => stack frame.

**Comment by asbjornu** [comment]
@marcomorain That sounds like a good direction. If you have time to work on this, I would highly appreciate a pull request! 👍

**Comment by marcomorain** [comment]
I've been looking into some call-stacks containing async calls today, and I wanted to document what I see.

A stack-frame in Sentry has the following form when the function has the async modifier:

```
Flipdish.Domain.DomainModel.Services.OrderService+<SubmitOrder>d__14 in MoveNext at line 241:13
```

The function would look like this if you removed the async modifier:

```
Flipdish.Domain.DomainModel.Services.OrderService in SubmitOrder at line 241:13
```

I'm thinking along the lines of:

If the module name ends with `\+<(\w*)>d__\d*` and the function name is `MoveNext` then we can remove the end of the module name (the bit that matches the regex) and change the function name to the identifier captured by the regex (`\w*`).

**Comment by marcomorain** [comment]
Here is an example screenshot of our callstacks:

<img width="915" alt="screen shot 2016-09-03 at 12 43 16" src="https://cloud.githubusercontent.com/assets/448001/18224614/050b7a7e-71d4-11e6-88b4-4d093df03682.png">

The bottom two frames are normal functions, and the others are async functions. I'm trying to make all levels of the callstack look like the bottom two.

**Comment by asbjornu** [comment]
@marcomorain 👍

**Comment by marcomorain** [comment]
I had a quick stab at this, adding the following to class `ExceptionFrame`

```C#
 /// <summary>
/// Demangle function names create when C# compilers lower newer language features such as async/await calls.
/// </summary>
private void Demangle() {
  if (Function == "MoveNext" && Module != null) {

  // Clean up the the `async` state machine calls.
  // Search for the function name in angle brackets followed by d__<digits>.
  //
  // Change:
  //   RemotePrinterService+<UpdateNotification>d__24 in MoveNext at line 457:13
  // to:
  //   RemotePrinterService in UpdateNotification at line 457:13

  var mangled = @"^(.*)\+<(\w*)>d__\d*$";
  var match = Regex.Match(Module, mangled);
  if (match.Success && match.Groups.Count == 3) {
    Module = match.Groups[1].Value;
    Function = match.Groups[2].Value;
  }
}
```

### Before

![original](https://cloud.githubusercontent.com/assets/448001/18383509/e2ad485a-767d-11e6-8479-6cc3b9cd21e3.png)


### After
![new](https://cloud.githubusercontent.com/assets/448001/18383504/dddcf352-767d-11e6-9e8b-bfe1279bbd4f.png)

**Comment by marcomorain** [comment]
The code in question looks like this:

```C#
    private static async Task<int> Recurser(int stackframes) {
        return await DivideByZero(stackframes);
    }

    private async static Task<int> DivideByZero(int stackFrames = 10)
    {
        if (stackFrames == 0)
        {
            var a = 0;
            return 1 / a;
        }
        else {
            return await Recurser(--stackFrames);
        } 
    }
```

**Comment by marcomorain** [comment]
The code in question looks like this:

```cs
    private static async Task<int> Recurser(int stackframes) {
        return await DivideByZero(stackframes);
    }

    private async static Task<int> DivideByZero(int stackFrames = 10)
    {
        if (stackFrames == 0)
        {
            var a = 0;
            return 1 / a;
        }
        else {
            return await Recurser(--stackFrames);
        } 
    }
```

**Comment by asbjornu** [comment]
A huge improvement! :shipit:

**Comment by marcomorain** [comment]
I have opened a PR - https://github.com/getsentry/raven-csharp/pull/155

**Comment by marcomorain** [comment]
I found a table describing the implementation of the mangling: http://stackoverflow.com/questions/2508828/where-to-learn-about-vs-debugger-magic-names

**Comment by asbjornu** [comment]
@marcomorain: Excellent! Is there anything we should do on our side to align us closer with Eric Lippert's excellent description, or are we fine as is, you think?

**Comment by marcomorain** [comment]
I think we are fine as we are, but having this link here will hlpe us find in future if we want to handle more cases.

I went looking through our (Flipdish) exceptions in Sentry, and I could only find mangled function names that match what we covered in #164 in the stack-frames from out app. I could find uses of the other constructs listed in functions in `System.Web.Mvc.Async.`, but not in our code.

I'd love to spend some time covering other cases, but it might not be the best use of my time :)

Here is a typical stack trace for us:

```
Flipdish.Domain.DomainModel.Services.OrderService+<CancelOrderAsync>d__22 in MoveNext at line 785:17
System.Runtime.CompilerServices.TaskAwaiter in ThrowForNonSuccess at line 38:0
System.Runtime.CompilerServices.TaskAwaiter in HandleNonSuccessAndDebuggerNotification at line 40:0
System.Runtime.CompilerServices.TaskAwaiter in GetResult at line 11:0
Flipdish.Web.Controllers.OrderController+<CancelOrder>d__20 in MoveNext at line 252:13
System.Runtime.CompilerServices.TaskAwaiter in ThrowForNonSuccess at line 38:0
System.Runtime.CompilerServices.TaskAwaiter in HandleNonSuccessAndDebuggerNotification at line 40:0
System.Web.Mvc.Async.TaskAsyncActionDescriptor in EndExecute
System.Web.Mvc.Async.AsyncControllerActionInvoker+<>c__DisplayClass37 in <BeginInvokeAsynchronousActionMethod>b__36
System.Web.Mvc.Async.AsyncControllerActionInvoker in EndInvokeActionMethod
System.Web.Mvc.Async.AsyncControllerActionInvoker+AsyncInvocationWithFilters in <InvokeActionMethodFilterAsynchronouslyRecursive>b__3d at line 20:0
System.Web.Mvc.Async.AsyncControllerActionInvoker+AsyncInvocationWithFilters+<>c__DisplayClass46 in <InvokeActionMethodFilterAsynchronouslyRecursive>b__3f at line 134:02
System.Web.Mvc.Async.AsyncControllerActionInvoker in EndInvokeActionMethodWithFilters
System.Web.Mvc.Async.AsyncControllerActionInvoker+<>c__DisplayClass21+<>c__DisplayClass2b in <BeginInvokeAction>b__1c
System.Web.Mvc.Async.AsyncControllerActionInvoker+<>c__DisplayClass21 in <BeginInvokeAction>b__1e
```

You can see that #164 covers these cases.

**Comment by marcomorain** [comment]
We could fix up some items like this:

`System.Web.Mvc.Async.AsyncControllerActionInvoker+<>c__DisplayClass21 in <BeginInvokeAction>b__1e`

what's happening here is that we are in the class `System.Web.Mvc.Async.AsyncControllerActionInvoker`, function `BeginInvokeAction`, calling an anonymous function.

I don't know how best to represent this in Sentry. Maybe include the function in the module name?

Module = `System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeAction`
Function = `<anonymous>`

**Comment by asbjornu** [comment]
@marcomorain: That example would have been nice to demangle as well, yes! But having `BeginInvokeAction` in the `Module` feels wrong. How about writing `Function` up as any of these?

* `BeingInvokeAction { ƛ }`
* `BeginInvokeAction { () ⇒ _ }` 
* `BeginInvokeAction { () => _ }` 
* `BeginInvokeAction { <lambda> }`
* `BeginInvokeAction { (lambda) }`
* `BeginInvokeAction { x ⇒ x }`
* `BeginInvokeAction { x => x }`

**Comment by marcomorain** [comment]
@asbjornu I like `BeingInvokeAction { ƛ }` and `BeginInvokeAction { <lambda> }`.

The other forms ( `x => x`) would be slightly missleading depending on the arity of the lambda. Fixing this would require us to read the arity of the anonymous block from the reflection metadata, so that we could show a function of arity 2 as `(x, y) => z`.
