### ISSUE TITLE
Support for .net 3.5

### ISSUE THREAD

**Issue by aldav82** [getsentry/raven-csharp#151]
Hello, somewhat, I can't get RavenSharp to work under a simple .net 3.5 project because all the packages I seem to find on GitHub target .net 4.0. How can I target .net 3.5 and still use RavenSharp?

**Comment by asbjornu** [comment]
@aldav82 The solution is set up to build .NET 4.0 and 4.5, so it shouldn't be too hard to add support for 3.5. If you're up for it, I'd happily accept a PR implementing it.

**Comment by aldav82** [comment]
@asbjornu Ok, I would like to help because I am interested in giving support to 3.5. However, I am relatively new to Github, and I'm not quite sure what are the required steps to crear a Pull Request. What should I do?

**Comment by asbjornu** [comment]
@aldav82, [this article should get you up and running](https://guides.github.com/activities/forking/), but if you have any questions, please don't hesitate to throw them my way! :smiley:

**Comment by asbjornu** [comment]
Implemented in d4477018f02c8695eed507f0d9758c6ef0ea8d4f.
