### ISSUE TITLE
issue with Newtonsoft.Json dependencies

### ISSUE THREAD

**Issue by junos** [getsentry/raven-csharp#154]
There are the steps to re-produce the issue we have:
1. Our project use .net 4.6.1
2. install sharpRaven 2.1.0 with NewtonSoft.Json 9.0.1
3. When call await ravenClient.CaptureAsync, it always throws say NewtonSoft.Json 6.0.0.0 can not be found.

Could you explain why this happened?

Thanks,
Jun

**Comment by asbjornu** [comment]
How did you end up with version 9.0.1 of NewtonSoft.Json? Downgrade it to version 6 and it should work fine. If you need version 9 for other stuff in your project you have a dependency problem NuGet isn't equipped to handle.

**Comment by samukce** [comment]
You can use the new versions newtonsoft if you put on app.config of the
project or create assemvlyResolverHandler.

Em 8 de set de 2016 6:27 PM, "Asbjørn Ulsberg" <notifications@github.com>
escreveu:

**Comment by samukce** [comment]
@junos  It worked for you?

**Comment by samukce** [comment]
```c#
using System;
using System.IO;
using System.Reflection;

namespace ProjectExample {
    public class AssemblyResolver {
		private const string NewtonsoftName = "Newtonsoft.Json";

        public static Assembly MyResolveEventHandler(object sender, ResolveEventArgs args) {
            var directoryAssembly = Path.GetDirectoryName(Assembly.GetAssembly(typeof(AssemblyResolver)).Location);

            var nameAssembly = args.Name.Split(',')[0];

            if (nameAssembly.StartsWith(NewtonsoftName, StringComparison.InvariantCultureIgnoreCase)) {
                var plugin = Path.Combine(directoryAssembly, nameAssembly) + ".dll";
              
                if (File.Exists(plugin))
                    return Assembly.LoadFile(plugin);
            } 

            return null;
        }
    }
}

`

**Comment by Hyldahl** [comment]
Hooking into the AssemblyResolve Event is one way to go.

You would normally solve versioning conflicts by configuring assembly binding redirects in the app.config file like so:

```<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

(The nuget package manager will automatically create the configuration changes when installing a nuget package)

**Comment by asbjornu** [comment]
Since two solutions have been provided and no response has been given from @junos, I'm closing this. Reopen if this is still a problem.
