### ISSUE TITLE
ravenClient.release

### ISSUE THREAD

**Issue by dualznz** [getsentry/raven-csharp#158]
hi, love this sdk, but there is no documentation on how to use it other than parsing the dsn and capturing the exceptions.

what i would like to know is whats the .release string variable, ive called it and it does not do anything.

any help, i would love for the ravenClient to be able to post out releases.

etc from sentry docs

Release Tracking 

```
// See SDK documentation for language specific usage.
Raven.config('your dsn', {
  release: 'relcode'
});
```

https://docs.sentry.io/hosted/api/releases/

**Comment by dcramer** [comment]
@dualznz we document this a bit in various places of Sentry, but its not clear here. The C# client is a community supported SDK, but we're absolutely interested in improvements.

The release is *usually* the version of your app. Often this is something like the git sha value.

Setting this will open up a few various features around release tracking.

![screenshot 2016-09-16 22 21 40](https://cloud.githubusercontent.com/assets/23610/18606158/fb0f9df6-7c5b-11e6-858d-467d6f6126e0.png)

**Comment by Kordonme** [comment]
We added the new release hook to our deployment cycle and they show upin Releases tab under a project. However, no info about when the error was seen/last seen is shown. Are we required to send the release along with exception sent? Shouldn't Sentry be able to figure it out based on current release?

**Comment by dcramer** [comment]
Current isn't really a safe concept so we require the release metadata to be passed via the SDK. The hooks are primarily for augmenting and adding additional details about releases,which aren't heavily used yet.

**Comment by asbjornu** [comment]
The release can be set on `RavenClient.Release` and is sent to the Sentry API on every event that is captured:

https://github.com/getsentry/raven-csharp/blob/3c30a19c953744afb99ff4a618c6c97a062597e7/src/app/SharpRaven/RavenClient.cs#L156-L159

This was implemented years ago and has been working fine. Closing.
