### ISSUE TITLE
Support for Universal App Platform

### ISSUE THREAD

**Issue by kdazzle** [getsentry/raven-csharp#162]
Tried to install SharpRaven for my solution through the Visual Studio extension and got this error:

```
SharpRaven 2.1.0 is not compatible with UAP,Version=v10.0.
Some packages are not compatible with UAP,Version=v10.0.
SharpRaven 2.1.0 is not compatible with UAP,Version=v10.0 (win10-arm).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm).
SharpRaven 2.1.0 is not compatible with UAP,Version=v10.0 (win10-arm-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
SharpRaven 2.1.0 is not compatible with UAP,Version=v10.0 (win10-x64).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64).
SharpRaven 2.1.0 is not compatible with UAP,Version=v10.0 (win10-x64-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
SharpRaven 2.1.0 is not compatible with UAP,Version=v10.0 (win10-x86).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86).
SharpRaven 2.1.0 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).
```

Not sure if that's something that's on the roadmap.

**Comment by asbjornu** [comment]
@kdazzle: Nothing on the roadmap, but if you have any idea on what the problem might be and how to fix it, we're at least a step closer. :smile:

**Comment by kdazzle** [comment]
Heh, I kind of figured it was an intentional choice for some reason. 

My knowledge of C# is pretty weak, but I'll take a quick look and see if anything is obvious. In the meantime, I ended up using this: https://www.nuget.org/packages/DeveloperInTheFlow.Sentry.UWP

**Comment by asbjornu** [comment]
@kdazzle Thanks for pointing out the existence of that library. I hope we can combine forces somehow!

**Comment by ryanvalentin** [comment]
Since UWP apps have used .NET native for a while now, the stacktraces generated from release builds aren't particularly helpful. Having debug symbol support in #85 would fix this (I've moved to HockeyApp for my apps because they support debug symbols).

**Comment by asbjornu** [comment]
@ryanvalentin: Have you tried @kdazzle'z library? If that works, I would love to have that ported over to SharpRaven somehow.

**Comment by asbjornu** [comment]
If .NET Core support may be of any help, [SharpRaven version `2.2.1-unstable0059`](https://www.nuget.org/packages/SharpRaven/2.2.1-unstable0059) was just published to NuGet.org. It has a .NET Core build target inside of it. Please test it and report back your status. Thanks!

**Comment by bruno-garcia** [comment]
Being tracked here: https://github.com/getsentry/sentry-dotnet/issues/131
