### ISSUE TITLE
Breadcrumb Support

### ISSUE THREAD

**Issue by flower189** [getsentry/raven-csharp#167]
Is it on the road map to add support for the breadcrumbs feature in sentry?
https://docs.sentry.io/learn/breadcrumbs/

**Comment by samukce** [comment]
it was done. :) You can install the unstable version to use.

Em 1 de nov de 2016 6:58 AM, "James" <notifications@github.com> escreveu:

**Comment by flower189** [comment]
Ah! Thanks, I hadn't noticed it in the repository.
Do you have any idea when this might make it into stable?

**Comment by asbjornu** [comment]
@flower189: Please test [the latest unstable release](http://www.nuget.org/packages/SharpRaven/2.1.1-unstable0111) and report your experience with it back here. If you (and everyone else) are content with how it works, I guess we can publish a stable version of that some time this week.

**Comment by ZubyH** [comment]
If I create a new breadcrumb and use AddTrail() immediately after after breadcrumb, then the logging looks good in Sentry when it's thrown.

However the AddTrail method implies that I can trail breadcrumbs in bulk? But the class definition only allows me to add one breadcrumb at a time to the trail.

**Comment by asbjornu** [comment]
@samukce: As the main developer of this feature (#131), what's your take on what @ZubyH writes? I don't have time to look at the code at the moment.

**Comment by ZubyH** [comment]
In the same sense, it would be good to have one breadcrumb class object, where the Message property is a List<string>. That way i can have one breadcrumb object per controller method (in MVC terms), and continually add messages to the Message List<string>. As soon as my method encounters an error, I fire the AddTrail method for this breadcrumb, and the List<string> is passed to Sentry as a list of seperate breadcrumb entries.

Currently, as the code is now I can't see another way of using breadcrumbs without creating a new object for each message, and then firing AddTrail().

What do you think?

**Comment by ZubyH** [comment]
List of strings**

**Comment by asbjornu** [comment]
@ZubyH: Since we're only in pre-release with this functionality, I think we have room to improve it. If you want to submit a pull request showing how you would like it to work, I think it would be easier to discuss it.

**Comment by ZubyH** [comment]
Okay sure, that sounds like a good idea

Regards,
Zubair

**Comment by samukce** [comment]
Hi all,

I think that could you register the RavenClient in your container of
dependencies injection and each class that you need register something you
can use revenClient.AddTrail(..).
Or, if you use some frameworks log(log4net, nlog,...) you could create a
provider to concentrate all in one point.
If we create one addRangeTrail, our Framework Will Lost the management
about the counter of the items logged, the what build some memory leak or
something else.
But if you want to create a PR we can analyse your point of view. :)

Em 10 de nov de 2016 8:44 AM, "ZubyH" <notifications@github.com> escreveu:

**Comment by asbjornu** [comment]
@ZubyH: How are things working out? Can this issue be closed? If so, I feel that we have had a long enough period with testing of the pre-released package that we can declare it stable. Objections?

**Comment by ZubyH** [comment]
Hi,

Sorry I've been caught up porting my apps to AngularJS so haven't had much
time to look into this.

Do you have any examples of how you actually use breadcrumbs? Maybe I'll
find what I'm looking for by using the crumbs a different way?

Would be good to see another way, then I'll know whether I have a real
issue or not

Regards,
Zubair

**Comment by asbjornu** [comment]
@samukce: Could you please provide an example of how the breadcrumbs work, preferably as a pull request to the documentation? 😃

**Comment by samukce** [comment]
Sure. I gonna do this week.

**Comment by samukce** [comment]
Please, @asbjornu,  Look it and let me know if I can improve something. PR: https://github.com/getsentry/raven-csharp/pull/169

**Comment by asbjornu** [comment]
@samukce: Thanks! I'll close this, then.
