### ISSUE TITLE
Post data is always null

### ISSUE THREAD

**Issue by twilly86** [getsentry/raven-csharp#170]
See screen shot, the post data is null.  I'm using  MVC 5 and .net 4.6.1.

I'm logging exceptions in a custom error attribute.

![2016-12-28_8-35-37](https://cloud.githubusercontent.com/assets/3496838/21525189/d446a2c8-ccd8-11e6-8f67-b9f06d775aef.png)

Any ideas?  Let me know if I can provide any other info to help troubleshooting.

**Comment by asbjornu** [comment]
@twilly86: Which version of SharpRaven are you using? Can you try upgrading to [version 2.1.1-unstable0113](https://www.nuget.org/packages/SharpRaven/2.1.1-unstable0113) and see if it behaves better?

**Comment by asbjornu** [comment]
I think this was fixed in #121. Reopen if this is still a problem.

**Comment by twilly86** [comment]
yes, that fixed it thanks
