### ISSUE TITLE
Custom Fingerprint with Capture(SentryEvent) Method

### ISSUE THREAD

**Issue by barbosab** [getsentry/raven-csharp#173]
I am trying to figure out how to set a custom fingerprint for a given warning/exception, and it appear in the new method structure: `public string Capture(SentryEvent @event)`, but it appears that there is no way to do so, even though the older, obsolete methods had this capacity.

Our use case is for web exceptions.  Basically, what is happening is when we have a web call to a 3rd party fail, it returns the same stack trace with a different message code (401, 403, etc).  Because these all have the same stack trace, they get rolled up as one, even though they can be drastically different errors.

I looked into the code for the RavenClient, and it appears the reason this can't be set is SentryEvent has an internal set for Fingerprint:
`internal set { this.fingerprint = value ?? new List<string>(); }`

The easy fix for this is remove the internal - is there any reason this isn't possible/desirable?

**Comment by asbjornu** [comment]
Any reason why you can't use the [`SentryEvent.Fingerprint` property](https://github.com/getsentry/raven-csharp/blob/develop/src/app/SharpRaven/Data/SentryEvent.cs#L96)?

**Comment by barbosab** [comment]
Ahh, I knew I had to be missing something!  Thank you.
