### ISSUE TITLE
Support dsn without private keys

### ISSUE THREAD

**Issue by GeertvanHorrik** [getsentry/raven-csharp#174]
According to the docs, one should use the public-only key dsn when using clients. However this causes the RavenClient to throw an exception since it requires the private key.

Happy to do a PR, but want to discuss this first.

**Comment by asbjornu** [comment]
I've never used a public key myself, so I'm not sure what its intended use is and what implications it has for SharpRaven. I'm just a maintainer of this library and not affiliated with @getsentry, so some elaboration would be appreciated. 😃

**Comment by dcramer** [comment]
The public key is not supported outside of browser JavaScript. There's no security concerns with the secret key and the only difference is we have some additional abuse protection for JavaScript clients.

**Comment by GeertvanHorrik** [comment]
Thanks for the additional explanation, then we can safely "expose" the private key. It might be good to add this to the docs, since the terms "semi-secret" and "use public key only for clients" was misleading me (but it might be just me, not sure).

**Comment by BenWoodford** [comment]
Definitely with @GeertvanHorrik on this one, Raven not supporting public DSN is weird, as it's VERY easy for someone to extract the DSN from a C# application. Literally just a matter of popping only ILSpy and decompiling the application/DLL.

**Comment by 0xdeafcafe** [comment]
I think the confusion comes from the fact sentry is primarily used for monitoring web applications, so the issue of being able decompile the application and extract the DSN doesn't surface.

**Comment by dcramer** [comment]
The worst they can do is send fake data and there's simply no way we can prevent it. We could expand docs, but each SDK asks for a specific key and is generally inflexible. At the end of the day if there's an abuse problem you can always block an IP or suspend the key.
