### ISSUE TITLE
Sign assembly

### ISSUE THREAD

**Issue by nerfpops** [getsentry/raven-csharp#176]
There's tools to automatically do this, but it makes it hard to share code between projects. A signed version would be great!

**Comment by asbjornu** [comment]
If you have a solution that can automate this the entire way from compile time through the build process to publishing on NuGet and that in no way interferes with the non-signed package, I would happily accept a pull request for this. 😃

**Comment by asbjornu** [comment]
As explained in jbogard/MediatR#86, you can use [Strong Namer](https://github.com/dsplaisted/strongnamer) to add a strong name to any assembly at build time.

**Comment by bruno-garcia** [comment]
@nerfpops  We've release a new version of the new .NET SDK which contains **strong named** assemblies:

https://github.com/getsentry/sentry-dotnet/releases
