### ISSUE TITLE
Catch exception during the creation of JsonPacket

### ISSUE THREAD

**Issue by skyline75489** [getsentry/raven-csharp#180]
The code [here](https://github.com/getsentry/raven-csharp/blob/develop/src/app/SharpRaven/RavenClient.cs#L224) may throw exceptions. I think we should catch it and leave it to `HandleException`.

**Comment by asbjornu** [comment]
Do you have examples of what type of exceptions might be thrown? I don't mind a `try/catch` in there, I'm just curious.

**Comment by skyline75489** [comment]
I'm new to this project so I was trying to build a custom `Extra` using:

```csharp
event.Extra = "This is my custom string";
```
This gives me exception when constructing JsonPacket. After a little research I realize I should be using:

```csharp
exception.Data.Add("SomeKey", "SomeValue");
```

Still, I'd expect `ErrorOnCapture` can handle this kind of situation.

**Comment by asbjornu** [comment]
Indeed. Would you fancy creating a pull request with a test provoking this error and fixing it as well?

**Comment by skyline75489** [comment]
Sure. I'll try to make to PR later.
