### ISSUE TITLE
Fingerprint property is internal on SentryEvent and there is no way to set it

### ISSUE THREAD

**Issue by octaviobffernandes** [getsentry/raven-csharp#183]
When I wanted to add a custom fingerprint to an event (as a last resort) to force aggregation, I used to do ravenClient.CaptureMessage() or ravenClient.CaptureException() passing the fingerprint obj as an argument.

Now these two methods are marked as obsolete and it is recommended to use only ravenClient.Capture(event) passing the event itself as argument. And the FingerPrint property is internal on the event class.

Is there any way to customize the fingerprint on the current version of shap raven?

**Comment by asbjornu** [comment]
The [`SentryEvent.Fingerprint` property](https://github.com/getsentry/raven-csharp/blob/develop/src/app/SharpRaven/Data/SentryEvent.cs#L96) does not look `internal` to me?

**Comment by octaviobffernandes** [comment]
Exactly this one, @asbjornu . The setter is internal.

**Comment by asbjornu** [comment]
Yes, but the property is `public` and is a `IList`. Can't you `.Add()` to it?

**Comment by octaviobffernandes** [comment]
Yes, that's ok.. I was trying to avoid a NullReferenceException, but I see now the list is being initialized on the private constructor. I will close the issue. Thanks!

**Comment by asbjornu** [comment]
👍
