### ISSUE TITLE
CaptureAsync for .NET4

### ISSUE THREAD

**Issue by skyline75489** [getsentry/raven-csharp#184]
With the help of [Microsoft.Bcl](https://www.nuget.org/packages/Microsoft.Bcl/) package we are able to use `Task`. Can we maybe also add `CaptureAsync` for .NET 4?

**Comment by asbjornu** [comment]
Sure, if you're able to add a conditional reference to it when stuff is compiled for .NET 4.0, you can probably change the `#if` statements to include the `Async` methods when compiling .NET 4.0. Want to tackle this in a PR?

**Comment by skyline75489** [comment]
The `async` feature will be fully supported after KB2468871 is installed. This is simply frustrating and confusing for anyone who want to work with Microsoft.Bcl.Async. With this in mind I'd rather just leave this be.

**Comment by asbjornu** [comment]
Whether KB2468871 is installed or not only affects code consuming SharpRaven, not SharpRaven itself. We can compile in support for `CaptureAsync` and link against `Microsoft.Bcl` for .NET 4.0 regardless. It's up to you whether you want to submit a PR for this or not, but I believe it would work just fine.

The only drawback would be that .NET 4.0 users with KB2468871 installed would get a reference to `Microsoft.Bcl` that they in theory could do without, but right now they don't have `CaptureAsync` at all, which I assume is a worse situation?

**Comment by skyline75489** [comment]
Here's some background that I forgot to mention: If the client doesn't have KB2468871, `Task<T>` still works, but any usage of `async` and `await` will cause craaaaash. Yeah. A pretty annoying gotcha.
