### ISSUE TITLE
Dll Required Newtonsoft.Json 6.0.0 in order to load

### ISSUE THREAD

**Issue by eduxavier** [getsentry/raven-csharp#187]
I've tryied install the client in my app. Unfortunatly it cannot be load. Raven client requires a Newtonsoft.Json 6.0.0 (my was 4.5). Then I tried same version but couldn't find.

https://www.nuget.org/packages/Newtonsoft.Json/6.0.1

Any recommendation?

**Comment by samukce** [comment]
Hey Eduardo, should works with the last version of the newtonsoft. You can
tray install the last one and try again.

Samuel Pereira
Senior Systems Analyst

c. +55 85 9 8883.1368

skype samuel.p.araujo
l. br.linkedin.com/in/samuelpereiraaraujo

g. github.com/samukce

**Comment by asbjornu** [comment]
@eduxavier: The `6.0.0` version that .NET refers to is probably the `AssemblyVersion`, not the NuGet package version. The `6.0.1` NuGet package you've found most likely has `6.0.0.0` as its `AssemblyVersion`.

**Comment by eduxavier** [comment]
I've migrated to latest version and could use Raven. But I don't kike this approach as it forced me to do extra configuration and spend time. But thank you guys for the help.
