### ISSUE TITLE
newtonsoft json reference error?

### ISSUE THREAD

**Issue by plsft** [getsentry/raven-csharp#190]
System.IO.FileNotFoundException occurred
  HResult=0x80070002
  Message=Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
  Source=SharpRaven
  StackTrace:
   at SharpRaven.RavenClient.<CaptureAsync>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at SharpRaven.RavenClient.CaptureAsync(SentryEvent event)
   at Util.Logging.LoggingClient.<LogInfo>d__6.MoveNext() in 

I have it referenced and it's in BIN as well as in app.config bound in the XML to v6: 

```xml
   <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>
```

**Comment by asbjornu** [comment]
Duplicate of #154. I guess you have a higher version of Newtonsoft.Json than `6.0.0.0` in your solution, which means you need to change the assembly redirect to include that version number and also to redirect it to that version number. If you have version `9.0.0.0` in your solution, the assembly redirect needs to look like this:

```xml
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
  <dependentAssembly>
    <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
  </dependentAssembly>
</assemblyBinding>
```

**Comment by plsft** [comment]
I'm familiar with assembly binding.  I've tried several versions of Newtonsoft.Json including 6, 9 and 10 to no avail. with each version I updated the app.config.

**Comment by plsft** [comment]
my app.config:
```
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>
```
![image](https://user-images.githubusercontent.com/13736152/30673453-3e96f670-9e41-11e7-908b-182c33fbd9d9.png)

usage:
![image](https://user-images.githubusercontent.com/13736152/30673461-4d771be8-9e41-11e7-86d1-1acfa41e9c1a.png)

exception:

![image](https://user-images.githubusercontent.com/13736152/30673483-67b9c104-9e41-11e7-9522-dea923f1ac6d.png)

**Comment by asbjornu** [comment]
There are no other projects or external references in your solution referencing another version of Newtonsoft.Json? Do you have more than one `.config` file in your output directory?

**Comment by plsft** [comment]
there are other config files in the bin folder however they are all bound to same v6 version. i just added newtonsoft.json directly as a ref to the project. it works now

**Comment by asbjornu** [comment]
@plsft: I'm glad you figured it out!
