### ISSUE TITLE
Add sampleRate parameter

### ISSUE THREAD

**Issue by HazAT** [getsentry/raven-csharp#191]
We've decided to add a `sampleRate` config parameter to all SDKs.
The concept of it is pretty straightforward, it should be a float between `0.0 - 1.0`. The value defines the likelihood of sending an event.

So here is an example from the Java SDK:
https://github.com/getsentry/sentry-java/blob/4df5218deab6c874458fa21ed696af503ea161ef/sentry/src/main/java/io/sentry/connection/RandomEventSampler.java#L45-L49

**Comment by bruno-garcia** [comment]
We've released the new SDK which solves this issue:

https://github.com/getsentry/sentry-dotnet/releases

https://www.nuget.org/packages/Sentry

I'll close this issue but please feel free to reopen or open one in the new repository if you have any issues integrating. We'll be happy to help you moving over to the new SDK.
