### ISSUE TITLE
Line numbers consistently wrong

### ISSUE THREAD

**Issue by joshingham** [getsentry/raven-csharp#192]
I'm finding that the line numbers reported to Sentry are wrong for every single event. I am in an MVC envrionment.

For example, in the attached file, which is the Raw from an event, the line in question is not in inside the Register Player method. There also seems to be no pattern that I can discern, for example that the line number is always the correct number plus 60 or something like that.

[Example Sentry Exception - Wrong Line Number.txt](https://github.com/getsentry/raven-csharp/files/1328801/Example.Sentry.Exception.-.Wrong.Line.Number.txt)

**Comment by asbjornu** [comment]
If you look at the source code:

https://github.com/getsentry/raven-csharp/blob/develop/src/app/SharpRaven/Data/ExceptionFrame.cs#L60

You can see that we fallback to `StackFrame.GetILOffset()`, which does not correspond to a line number in a source file, but to the IL instruction offset on the stack.

If you use [dotPeek](https://www.jetbrains.com/decompiler/), you can decompile the `DLL` file and enable "IL comments in decompiled code" to see how the IL offset corresponds to the source code. It's not perfect, but it's better than nothing.

**Comment by joshingham** [comment]
Thanks, that's good to know. I don't think it's clear in Sentry that this is what is required to get the reported line number to match up to the actual line number. I'll get in touch with them.
