### ISSUE TITLE
SharpRavenPCL

### ISSUE THREAD

**Issue by kodejack** [getsentry/raven-csharp#193]
I'm currently trailing Sentry for Xamarin Form project. However I cannot get it to Build on Android and it crashes at run time on iOS.

`/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2,2): Error: Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'SharpRavenPortable, Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
`

The project is targeting NetStandard 1.3 with support Profile111

**Comment by asbjornu** [comment]
#132, #145, #163, #168 and #189 all attempt to tackle this problem in one way or another. I'd say #189 is closest, so I hope we can get an AppVeyor build running there shortly and get it ready for merging.

**Comment by knocte** [comment]
I'm having similar problems as @kodejack .

@asbjornu looks like #189 has been merged, so is this usable if I clone last SharpRaven from git (instead of using Nuget)?

**Comment by asbjornu** [comment]
You should be able to download the [`.nupkg` artifacts from the latest AppVeyor build](https://ci.appveyor.com/project/sentry/raven-csharp/build/Branch.develop.Sha.3c30a19c953744afb99ff4a618c6c97a062597e7/artifacts) and use those. Please let me know how that works.

**Comment by asbjornu** [comment]
[SharpRaven version `2.2.1-unstable0059`](https://www.nuget.org/packages/SharpRaven/2.2.1-unstable0059) was just published to NuGet.org. Please test it and report back your status. Thanks!
