### ISSUE TITLE
Sending data to Sentry from custom error aggregator

### ISSUE THREAD

**Issue by trurl123** [getsentry/raven-csharp#195]
I want to use raven-sharp from service that gives some information about exception that occured at other servers and applications. So I want to build JsonPacket by myself. Would you please make all proprties at ExceptionFrame as public?

**Comment by asbjornu** [comment]
Sure, pull requests are welcome!

**Comment by trurl123** [comment]
Created https://github.com/getsentry/raven-csharp/pull/197
