### ISSUE TITLE
Setting the User

### ISSUE THREAD

**Issue by Tibincrunch** [getsentry/raven-csharp#199]
I'm having trouble setting the user context, can someone help clarify the process? I've inherited the SentryUserFactory like so:

```
public class SentryUserOverride : SentryUserFactory
    {
        private readonly IHttpContextAccessor _context;

        public SentryUserOverride(IHttpContextAccessor context)
        {
            _context = context;
        }

        protected override SentryUser OnCreate(SentryUser user)
        {
            user.Username = _context.HttpContext.User.Identity.Name;
            return base.OnCreate(user);
        }
    }
```

I'm my Startup.cs I've registered the HttpContextAccessor:
`services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();`

I'm not sure what to do next. Thanks.

**Comment by Mitch528** [comment]
In Startup.cs you will also need to register the RavenClient:
```csharp
services.AddSingleton<IRavenClient, RavenClient>(s => new RavenClient(new Dsn("<your dsn>"),
        sentryUserFactory: new SentryUserOverride(s.GetService<IHttpContextAccessor>())));
```

You can then inject IRavenClient into your services and capture the exceptions using the client.

**Comment by Tibincrunch** [comment]
Perfect, everything is working as expected. Thanks for the quick response!
