### ISSUE TITLE
Raven-csharp is not working for windows c# in release mode

### ISSUE THREAD

**Issue by awesomehimanshu** [getsentry/raven-csharp#205]
**The remote server returned an error: (403) Forbidden.**

When i run my C# application in visual studio in debug mode .
All the error are logging in the sentry portal .
But when i create .exc of it and run as service the application is working fine also looging perfecting in window Event Viewer.

![image](https://user-images.githubusercontent.com/16804408/34974674-5a134e06-fab4-11e7-8a2a-f24083fc7427.png)

But the log is not logging in sentry .

**Note: In debug mode it work fine.**

![image](https://user-images.githubusercontent.com/16804408/34974902-4df74d60-fab5-11e7-8337-a3a4d1c876c1.png)

What can be the reason to not log in sentry ?

I check the exc code is working fine 
var error = new Exception('some error');
```
var ravenClient = new SharpRaven.RavenClient(objConfiguration.Service.SentryUrl);
                    error.Data.Add("Subject", subjectPrifix + subject.Replace("info : ", ""));
                    error.Data.Add("msg", msg);
                    error.Data.Add("logger", "ContentSyncService");
                    System.Console.log("step1");
                    var sentryevent = new SentryEvent(error);
                    sentryevent.Tags = tags;
                    var eventid = ravenClient.Capture(sentryevent);
                    System.Console.log("step1");
                System.Console.log(eventid);
```

In this code i get `eventid ` nothing . And `step1` and `step2` is printing inboth debug mode and exc .

If needed more information please tell ?

**Comment by asbjornu** [comment]
Are you 100% certain `objConfiguration.Service.SentryUrl` is the same for both release and debug builds and that it is the correct [DSN](https://docs.sentry.io/quickstart/#configure-the-dsn)?

**Comment by awesomehimanshu** [comment]
It is working . This issue has to do with my proxy and authentication issue , not related to this repo .

**Comment by senad004** [comment]
Hello All, I am using .NET framework 4.5.2 and using SharpRaven for capturing exception. It is working fine in debug mode and on IIS 7 . But not passing error to Sentry when I am using IIS 8 . Can you please help me to resolve this problem?

**Comment by bruno-garcia** [comment]
@senad004 could you please try the [new .NET SDK](https://github.com/getsentry/sentry-dotnet) which follows the Sentry [unified API](https://blog.sentry.io/2018/09/19/new-sdks-unified-python-javascript-dotnet-rust). 

If it still doesn't work, please open an issue on that repository.
