### ISSUE TITLE
Strongly Named Assembly

### ISSUE THREAD

**Issue by bleppard** [getsentry/raven-csharp#208]
I am writing an application that needs [strongly named assemblies](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies#why-strong-name-your-assemblies). When I build the app with ShrapRaven included in NuGet I get the following error.

`1>CSC : warning CS8002: Referenced assembly 'SharpRaven, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.`

It would be great to include a strong name option for the SharpRaven package.

**Comment by asbjornu** [comment]
Please use [StrongNamer](https://github.com/dsplaisted/strongnamer) to strong name SharpRaven yourself.

**Comment by bruno-garcia** [comment]
@bleppard We've release a new version of the new .NET SDK which contains **strong named** assemblies:

https://github.com/getsentry/sentry-dotnet/releases
