### ISSUE TITLE
Bug: Reset InputStream position (2.2.0)

### ISSUE THREAD

**Issue by brunoblank** [getsentry/raven-csharp#209]
Hi,

We have run into a problem with Sentry and Flourine. 

Flourine reads the input-stream in chunks, when Flourine logs in this process, it cannot continue consuming the InputStream as Sentry consumed it.

Regards
Bruno Blank

**Comment by brunoblank** [comment]
Will submit a PR shortly

**Comment by asbjornu** [comment]
Fixed by #215.
