### ISSUE TITLE
set RavenClient's defaultTags

### ISSUE THREAD

**Issue by jonmcoe** [getsentry/raven-csharp#211]
is there any way to properly set this field?

https://github.com/getsentry/raven-csharp/blob/develop/src/app/SharpRaven/RavenClient.cs#L50

https://github.com/getsentry/raven-csharp/blob/develop/src/app/SharpRaven/RavenClient.cs#L107

I don't see how. I am happy to PR an additional setter, constructor addition, or make this field public (don't really see why it is any different than, say `Release` or `Environment` in that respect). Wanted to ask if there is a current approach I am not noticing, and if not which of the above mentioned approaches would the maintainers prefer.

**Comment by bruno-garcia** [comment]
You can use the [public Tags property](https://github.com/getsentry/raven-csharp/blob/develop/src/app/SharpRaven/RavenClient.cs#L169).
You can use the `IDictionary.Add` method to add tags to it.

**Comment by jonmcoe** [comment]
ah. so i get the same dictionary and add all the tags i'd like in sequence, but cannot reassign it. that'll do. thanks
