### ISSUE TITLE
Noop implementation of IRavenClient

### ISSUE THREAD

**Issue by razzmatazz** [getsentry/raven-csharp#213]
I think it would be nice to have a no-op implementation of IRavenClient available as that helps with dependency injection on development builds where I don't want to have nulls injected but rather an implementation that does not send data anywhere.

Would it make sense to include it in main distribution?

I can make a PR for this, however I am not sure about the naming of the class.

**Comment by asbjornu** [comment]
Sure, that sounds neat. A PR would be appreciated! 😄

**Comment by razzmatazz** [comment]
@asbjornu ok, here is my first attempt at PR, #222 :)
