### ISSUE TITLE
How do I define a new release? How do I add PDBs?

### ISSUE THREAD

**Issue by Tsury** [getsentry/raven-csharp#216]
I saw nothing about it in the docs. I want to be able to create releases and see stacktraces, is this even possible?

**Comment by birdycn** [comment]
Hello,I'm a newcomer of GitHub. 
May I ask you a question, please.
Throug the [topic](https://github.com/sorrycc/blog/issues/55#issuecomment-359194843),you have successfully used svg-sprite-loader in roadhog2.0, how your webpack.config.js is configured.

My webpack.config.js is as follows, and it's report errors:require(...) is not a function.
`module.exports = {
  module: {
      loaders: [  
          {  
            test: /\.svg$/,
            loader: 'svg-sprite-loader'
          }  
      ]  
  } 
}  `

**Comment by Tsury** [comment]
That's the relevant part of my webpack config:

```
const SpriteLoaderPlugin = require('svg-sprite-loader/plugin');

module.exports = (webpackConfig) => {
  webpackConfig.module.rules.push({
    test: /\.svg$/,
    loader: require.resolve('svg-sprite-loader')
  });

  webpackConfig.plugins.push(
    new SpriteLoaderPlugin()
  );
...
...
...
};
```

I also  added /\.svg$/ to the exclude list of url-loader in roadhog code.

**Comment by asbjornu** [comment]
Release is set on the `RavenClient.Release` property. PDB support is tracked in #85, please subscribe to that issue if you want to follow its progress.
