### ISSUE TITLE
Easy integration with ASP.NET MVC

### ISSUE THREAD

**Issue by techniq** [getsentry/raven-csharp#23]
Once issue #17 is resolved, it would be nice if there was a nuget package to easily integrate exception handling with ASP.NET MVC apps, similar to https://github.com/alexanderbeletsky/elmah.mvc for Elmah.

I figure it should be a different project from raven-csharp (maybe raven-aspnet-mvc?), although I know the raven-python has Django/Flask/etc.  If it is a separate project, should it be part of the getsentry organization, or should I start it under my personal projects?

**Comment by asbjornu** [comment]
@techniq Please have a look at the `develop` branch. It should be in a state where adding a `SharpRaven.Mvc` project alongside the existing `SharpRaven.Nancy` project should be a piece of cake. I'd appreciate a pull request that at least has a beginning of something that might work, so I can move it forward to completion and roll it into a version `2.0` release of SharpRaven. Closing this in wait for a pull request.

**Comment by bartvanderwal** [comment]
Hi @techniq! Your code looks great. I'm trying to incorporate it into my app now.

One remark though, don't you need to add the new custom `ErrorAttribute` and `ExceptionFilterAttribute` to the filters instead of the default ones?

1. So for the MVC in 'Global.asax' 's `Application_Start()` don't you mean:
```csharp
    GlobalFilters.Filters.Add(new HandleErrorAttribute());
    GlobalFilters.Filters.Add(new RavenHandleErrorAttribute());
   // ...
```

instead of:
```csharp
    GlobalFilters.Filters.Add(new HandleErrorAttribute());
   // ...
```

2. And for WebApi controllers in the `Register` method of `WebApiConfig.cs` don't you mean
```csharp
    GlobalFilters.Filters.Add(new RavenHandleErrorAttribute());
```

instead of:
```csharp
    config.Filters.Add(new DefaultErrorExceptionFilterAttribute());
```

**Comment by techniq** [comment]
@bartvanderwal yes, that looks right. If you have time you could submit a PR to the project.

**Comment by asbjornu** [comment]
@bartvanderwal, @techniq a pull request would be highly appreciated. Don't worry about making a NuGet package and such; just make something that works for you along with one or more tests (the more, the better).

**Comment by kedare** [comment]
Any news about this ? It looks like there are no easy way to integrate ASP.NET with Sentry for now ?
Thanks

**Comment by bartvanderwal** [comment]
Ah I forgot about it. It's working fine for me.
I'll look into submitting something again.

Sentry doesn't seem to advocate it on their 'prices' page - it shows no free tier - but if you run theough their free trial then errors keep getting logged and they still send you email notofications.

It's pretty limited and I gues you wouldn't risk production grade stuff with this. But it works fine for me.

**Comment by kedare** [comment]
In our case, we have our own on premise Sentry setup (As it's very easy to setup).
I never tried it with DotNet already it's working very good with Python/Django apps, I'm hoping it would be as good with ASP.NET :)

**Comment by asbjornu** [comment]
@kedare: While there certainly could be something similar to the [SharpRaven.Nancy package](https://www.nuget.org/packages/SharpRaven.Nancy) for ASP.NET MVC, it would only be a convenience wrapper around the library and not something you couldn't build yourself. It should be fairly easy to add SharpRaven to any MVC project; explicit support in the form of a NuGet package shouldn't be necessary.

**Comment by Anandkumar2007** [comment]
rtertertreter
