### ISSUE TITLE
Send TimeZone information with Contexts data

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/raven-csharp#236]
As part of the Contexts interface, provide the TimeZone information with each event.

Sentry docs on the Context Interface: https://docs.sentry.io/clientdev/interfaces/contexts/

The most consistent API for this is `TimeZoneInfo.Local.Id` which has also been around for a while so no need for #ifdef

On CoreCLR, Linux and macOS, it'll return the 'Europe/Vienna' format.
On CoreCLR and CLR on Windows, it'll return the 'W. Europe Daylight Time' format.

For Mono and Linux under WSL, see:
mono/mono/issues/8267
Microsoft/WSL/issues/3109

**Comment by asbjornu** [comment]
dotnet/corefx#11897 seems relevant.

**Comment by bruno-garcia** [comment]
#237
