### ISSUE TITLE
Decouple Event Capture from Send

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [getsentry/raven-csharp#239]
Currently the collection of the [User and HttpRequest details](https://github.com/getsentry/raven-csharp/blob/develop/src/app/SharpRaven/RavenClient.cs#L333-L335) event properties is tied to the submission of the event to sentry which is less than ideal as it requires the request thread to make the http request.  I'd like to be able to capture the event with all its details on the request thread, then have another thread (that I manage) be responsible for getting these events to sentry. This would also allow for other modifications to the transport system like local disk caching or using a different transport mechanism entirely (like sqs). 

Currently PreparePacket is a protected internal method, only called by [Requester in its constructor](https://github.com/getsentry/raven-csharp/blob/4130daa36113646968c7b1b5b30ddc87ab7e320a/src/app/SharpRaven/Data/Requester.cs#L70). The following changes would solve for my use case

- Move the PreparePacket call out of the Requester constructor and into RavenClient 
- Add a new method to RavenClient that captures the event and returns it to the caller instead of sending it 
- Expose Send on RavenClient as a public method  

I'd be happy to put up a pr for this

**Comment by bruno-garcia** [comment]
The use case makes sense. Having the client write the event to a buffer (i.e BlockingCollection) to be consumed by a worker thread is used in other SDK's at Sentry too.

It'd be awesome to get a PR with this feature too. Perhaps one thing to clarify is how to do it.
I might be missing something but wouldn't be simpler to create an interface for `Requester` say `IRequester`, rename the current one to `HttpRequester` and a new one (that writes to the in-memory queue): `ProducerConsumerRequester`.

At that point we'd have two clients living in the app. The one registered with DI or somehow made available to the app which uses the `ProducerConsumerRequester`.

And the second one which will be reading off of the queue, and sending the data with `HttpRequester`. For that, RavenClient would need a `Func<IRequester>` or some factory in order get a Requester.

@asbjornu will hopefully be able to tell me if I'm totally lost here ;)

**Comment by chris-smith-zocdoc** [comment]
I think the design of the producer/consumer would require some more thought than I've put into this so far which is why I would want to hold off on that for a later pr. One complication is that the current `Capture` methods return the `eventId` of the sentry event.  

Either way I believe these are necessary changes
- Move the PreparePacket call out of the Requester constructor and into RavenClient
- create an interface for Requester say IRequester, rename the current one to HttpRequester


RavenClient could take a `Func<IRequester>` to get a requester but its odd to me that we need a new instance for each event. We could instead make the Requester independent of the event instance allowing us to use the same requester for all events, which might be necessary for the producer consumer thread anyway.

**Comment by bruno-garcia** [comment]
@chris-smith-zocdoc That sounds good.

I'm not sure about sharing the Requester, it makes sense to me but not sure how hard of a change it'd be considering the current design expects an instance per request (request is sent by invoking a method on it which depends on its state).

Our support for producer/consumer will happen eventually but if this change unblocks you, better not wait for us. We'll be happy to merge it in.

/cc @asbjornu @mitsuhiko

**Comment by bruno-garcia** [comment]
@chris-smith-zocdoc I started a proposal that hopefully will fulfill your requirements: #242 
Could you please let me know if that'd solve your problem? If so, we'll be prioritizing this work and shipping it with version 3.0.0

**Comment by chris-smith-zocdoc** [comment]
@bruno-garcia Yes it will. I'm looking over it now

**Comment by bruno-garcia** [comment]
Thanks! Feel free to join [Gitter](https://gitter.im/getsentry/raven-csharp) if you'd like to discuss in more details

**Comment by bruno-garcia** [comment]
@chris-smith-zocdoc 
We've been working on a new SDK which has a background worker-only approach.
The API is unified with JS, Rust and eventually all our SDKs. It contains a couple integrations that were built to verify the abstractions. More will come.

If you would give it a try, the repo is here: https://github.com/getsentry/sentry-dotnet/
Thanks in advance!

**Comment by chris-smith-zocdoc** [comment]
Thanks for the heads up @bruno-garcia I'll make sure we check it out the next time we upgrade the sdk

**Comment by bruno-garcia** [comment]
@chris-smith-zocdoc 
The new SDK sends events on a background task is been released.

https://github.com/getsentry/sentry-dotnet/releases

https://www.nuget.org/packages/Sentry

I'll close this issue but please feel free to reopen or open one in the new repository if you have any issues integrating. We'll be happy to help you moving over to the new SDK.
