### ISSUE TITLE
Connect to self-hosted Sentry?

### ISSUE THREAD

**Issue by johnknoop** [getsentry/raven-csharp#251]
Hi!

I couldn't figure out if Raven only work with the hosted version, or if you can specify you own hostname somehow?

**Comment by bruno-garcia** [comment]
You can connect to any instance of Sentry. Be that sentry.io or an on-premises one.
The DSN contains your organization/project-id and also the server endpoint.

**Comment by johnknoop** [comment]
Oh, I see. Thanks!

**Comment by bruno-garcia** [comment]
You're welcome! ;)
