### ISSUE TITLE
Question: Can this be used when app is offline

### ISSUE THREAD

**Issue by stefandevo** [getsentry/raven-csharp#255]
Hi, just checking, but when this library is used in Xamarin mobile apps, is there any way of getting logs when the device is offline; meaning, it will hold the logs until the device is back online again?

**Comment by bruno-garcia** [comment]
Not the C# integration but if its Xamarin Android you can integrate the Java SDK which allows that I believe and also the iOS should work with the Objective C SDK.
What kind of Xamarin app is it?

We'll will support on C# too hopefully soon.

**Comment by bruno-garcia** [comment]
Tracked here: https://github.com/getsentry/sentry-dotnet/issues/80
