### ISSUE TITLE
Wrong device architecture in SharpRaven.Data.Context.Device

### ISSUE THREAD

**Issue by mogikanin** [getsentry/raven-csharp#256]
We use raven-csharp in windows desktop app.
packages.cofig:
```
  <package id="SharpRaven" version="2.4.0" targetFramework="net461" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="net461" />
```

We are running x86 process on x64 Windows, and raven-csharp reports x86 architecture in Device section. 
I guess there is a typo on this line: https://github.com/getsentry/raven-csharp/blob/develop/src/app/SharpRaven/Data/Context/Device.cs#L215
There should be  `RuntimeInformation.OSArchitecture.ToString();`

**Comment by bruno-garcia** [comment]
You're right! 
`RuntimeInformation.ProcessArchitecture` should go into `App`.
