### ISSUE TITLE
Feature - Add UnhandledExceptionEventHandler

### ISSUE THREAD

**Issue by Herve-M** [getsentry/raven-csharp#266]
Hello,

I will be nice to have a (easy) solution to work with `AppDomain.UnhandledException` and other a-like. 

[NBug](https://github.com/soygul/NBug/blob/master/NBug/Handler.cs) have a nice list to see.

Herve-M

**Comment by bruno-garcia** [comment]
@Herve-M We're working on a [new SDK](https://github.com/getsentry/sentry-dotnet/) which already has that integration OOTB.
it's [possible to *disable* it though](https://github.com/getsentry/sentry-dotnet/blob/master/src/Sentry/SentryOptionsExtensions.cs#L31).

**Comment by bruno-garcia** [comment]
We've released the new SDK which solves this issue:

https://github.com/getsentry/sentry-dotnet/releases

https://www.nuget.org/packages/Sentry

I'll close this issue but please feel free to reopen or open one in the new repository if you have any issues integrating. We'll be happy to help you moving over to the new SDK.
