### ISSUE TITLE
Setting the user per Sentry Capture

### ISSUE THREAD

**Issue by odannyc** [getsentry/raven-csharp#267]
I'm trying to figure out how to set the user (id, name, email) when I catch an Exception and then capture it with the ravenClient.
I tried looking to see if there was a way to set the user through the `SentryEvent` but there seems to be no way.

Can someone lead me through the right way of setting a user? 

**Note**
I can't set the user when I create an instance of `RavenClient` because I don't have an instance of the user at that point in time.

**Comment by bruno-garcia** [comment]
Hi @odannyc,

SharpRaven has a `UserFactory` that is called in case the `JsonPacket` doesn't (already have a User set](https://github.com/getsentry/raven-csharp/blob/b43d392e055b5da823a4bbc91ad8739c635caf8e/src/app/SharpRaven/Data/JsonPacket.cs#L346).

We're working on a [new SDK](https://github.com/getsentry/sentry-dotnet) which has the same API across the other new SDKs.
It supports adding the user with the event. There's a [sample here](https://github.com/getsentry/sentry-dotnet/blob/master/samples/Sentry.Samples.Console.Customized/Program.cs#L160) which uses a `EventProcessor` but you can simply do: 

```csharp
var evt = new SentryEvent(exception);
evt.User = new User();
SentrySdk.CaptureEvent(evt);
```

You can also set the user to the `Scope`:

```csharp
SentrySdk.ConfigureScope(s => s.User = new User());
```

Any event sent after that will include the user. You can also `SentrySdk.PushScope` which returns a `IDisposable` to essentially *pop* the scope. This concept is the same to DI containers and loggers.
We're working on new docs to cover these concepts in details.

It's still in preview though but thankfully to the feedback of users we are able to add new features and make sure it works well. It would be great if you could also try it out and give us feedback.

If you would like to try the new SDK and have some questions, feel free to ping me on [gitter](https://github.com/getsentry/sentry-dotnet/).

**Comment by jwillmer** [comment]
Can we have the field `SentryEvent.User` in the SDK? I don't like to switch to an alpha to integrate users. Is there a way to set the user in the current SDK?

**Comment by bruno-garcia** [comment]
We might accept a PR here if you want to contribute but we're focused on the new SDK right now which already has this feature. It doesn't make sense to put effort into adding this here too.

We'll release the SDK next month. It already has over 2000 downloads and we haven't received a bug report for the latest release. I wouldn't call it an alpha although I agree the version number looks like one.

**Comment by jwillmer** [comment]
My workaround is to create a custom UserFactory and add it on `new RavenClient(dsn: dsn, sentryUserFactory: userfactory)`

**Comment by bruno-garcia** [comment]
Glad that works for you. As I mentioned before, with the new SDK you can set the user to the scope (say per web request or when a desktop app starts) and any event sent after that point will include the user.

**Comment by bruno-garcia** [comment]
We've released the new SDK which solves this issue:

https://github.com/getsentry/sentry-dotnet/releases

https://www.nuget.org/packages/Sentry

I'll close this issue but please feel free to reopen or open one in the new repository if you have any issues integrating. We'll be happy to help you moving over to the new SDK.

**Comment by jwillmer** [comment]
@bruno-garcia Could you point me to the feature/option?

**Comment by bruno-garcia** [comment]
@jwillmer no problem:

The simplest way IMO is to add it directly to the event:

```csharp
try
{
    SentrySdk.AddBreadcrumb("Doing something wrong");

    throw null;
}
catch (Exception e)
{
    SentrySdk.CaptureEvent(new SentryEvent(e)
    {
        User = new User
        {
            Email = "user@domain",
            Id = "021748e3-d91e-4ee1-a65d-1795a7f0611e",
            IpAddress = IPAddress.Loopback.ToString(),
            Username = "username"
        }
    });
}
```

Another way is to set it to the scope, so any subsequent events sent out will include that data (in this case, User):

```csharp
using (SentrySdk.PushScope())
{
    var username = "johndoe";
    SentrySdk.ConfigureScope(s => s.User = new User { Username = username } );

    SentrySdk.CaptureMessage("Message from " + username);

    SentrySdk.CaptureMessage("This is also a message from " + username);
}
```

The reason I `PushScope` here is to isolate this with another path of execution of the app. For example in a web server handling requests, if you didn't Push a new scope, you'd be always setting a new user to the scope shared across all requests. This is similar to Logging libraries Scopes and DI container Scopes.

Once the code gets out of the `using` block above, the scope we set the user `johndoe` to is dropped.

I hope this makes it a bit more clear. Let me know otherwise.
