### ISSUE TITLE
If there is any possibility to Compatible to .net 2.0 ?

### ISSUE THREAD

**Issue by ArthurRyan0803** [getsentry/raven-csharp#272]
my project is based on .net 2.0.

**Comment by bruno-garcia** [comment]
@ArthurRen .NET Framework 2.0 is replaced by .NET Framework 3.5 with any Windows machine that gets Windows Update.

Could you please explain what use case you have where an app can't be upgraded from .NET Framework 2.0 to 3.5?

**Comment by ArthurRyan0803** [comment]
@bruno-garcia 
emmm.... i'm a Chinese developer and there is still some people use win-xp computer ...
But never mind ,  i have modified some code in order to compatible with .net 2.0 by myself , and i havn't found any problem so far.

Just need to implement "Extension Method" & "TimeZoneInfo ".

**Comment by bruno-garcia** [comment]
@ArthurRen .NET Framework 3.5 is compatible with Windows XP:

https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies

**Comment by ArthurRyan0803** [comment]
@bruno-garcia 
In china , there are many kinds of "Windows XP" ，and some pirated Windows XP are not well compatible with .NET 3.5  or higher version，some users could not even install .net 3.5.

**Comment by bruno-garcia** [comment]
@ArthurRen Unfortunately the maintenance burden is not really worth it for us. Tooling wise it's also tricky, even to get a machine with CLR 2.0, which gets replaced by the 3.5 when the machine is 'Windows Updated'.

Microsoft released a lot in the last **13 years**, current version being .NET Framework 4.7.2 which is 12 version (3.5, 3.5 SP1, 4.0, 4.5, 4.5.1, 4.5.2, 4.6, 4.6.1, 4.6.2, 4.7, 4.7.1, 4.7.2) ahead of 2.0. On top of that, there's a new, multiplatform runtime (.NET Core) which had 4 releases already in the last two years. We must ensure we can support the new runtimes and doing so in combination with such an older version would be extremely hard.

In this case I'd suggest forking the project to add support to .NET Framework 2.0.
I'll make sure to point anyone asking for .NET Framework 2.0 towards that repo.
