### ISSUE TITLE
Unable to capture the execution time on Sentry

### ISSUE THREAD

**Issue by senad004** [getsentry/raven-csharp#275]
Hi All,

I am using SharpRaven dll for capturing errors, logger information in C#. Will Sentry capture method execution time? This will help me to focus on performance related things. Please help on this.

Note: I am using Log4Net for capturing execution time now. Now I am looking to replace it by Sentry. So I want all details that arre already captured in Log4Net.
Please share your suggestions.

**Comment by bruno-garcia** [comment]
@senad004 
Sentry's SDKs are designed to capture errors automatically and include as much relevant context as possible. It's not part of the SDK to track execution time of each method. Doing that could have a significant impact on your application's performance and it's usually only done for performance tuning.

If you already have the tracking done with log4net, we have a new .NET SDK which has a log4net integration:
Please check [the docs](https://docs.sentry.io/platforms/dotnet/log4net/) and also the [GitHub repo](https://github.com/getsentry/sentry-dotnet).

**Comment by senad004** [comment]
@bruno-garcia 
Thanks for your reply. I am trying to install sentry.Log4Net 1.0.0 and getting below exception. Do you have any idea on this? Will it require any additional assemblies?

Error - Could not install package 'Sentry.Log4Net 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by bruno-garcia** [comment]
The new SDK targets .NET Standard 2.0.
This is the same issue you raised on the other repo: https://github.com/getsentry/sentry-dotnet/issues/114

I advise upgrading your app to .NET Framework 4.7.2

**Comment by senad004** [comment]
Hi @bruno-garcia  I upgraded it already. But still getting the same issue. Can you please share the dll ? That may help

**Comment by bruno-garcia** [comment]
The message you shared says: 

>  You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2'

So the project still targets 4.5.2. On Project properties you can toggle that to .NET 4.7.2.

There's no need to deal with the DLLs directly when NuGet is used.
NuGet takes care of finding the right DLLs built depending on what your app targets (.NET Core, .NET Framework and the version)

**Comment by senad004** [comment]
Oh . Sorry I am updating with 4.6.1 . Let me install 4.7.2 framework and try it

**Comment by bruno-garcia** [comment]
4.6.1 should already work although Microsoft has recently advised updating to 4.7.2 due to some issues with 4.6.1 backported compatibility to .NET Standard 2.0.

**Comment by senad004** [comment]
Ok got it.

**Comment by bruno-garcia** [comment]
Closing as it seems done. Feel free to reopen (ideally in the right repo getsentry/sentry-dotnet)
