### ISSUE TITLE
Unity 2017 with .NET 3.5 not send events to Sentry

### ISSUE THREAD

**Issue by adri21112** [getsentry/raven-csharp#277]
Hi.
I am working in a Android project with unity 2017 and .NET 3.5 (this is mandatory)
So I try to work with Sentry with Raven-csharp integration. The Nuget package its instaled without errors and the app runs perfect. But the Sentry platform doesn't recibe the post and the android monitor doesn't show errors.

This is my first code:
`
ravenClient = new RavenClient("my_project_url");	
string result = ravenClient.Capture(SentryEvent("hello world"));
`
The capture function returns null

I try this with the last stable version (2.4.0) and the  2.4.1-unstable0015.

Some suggestion?
Thanks for your attention.

**Comment by bruno-garcia** [comment]
@adri21112 `SharpRaven` doesn't support Unity.
We've made a first release of our [sentry.unity.lite SDK](https://github.com/getsentry/sentry-unity).
 
Please use that one instead.
