### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by danbopes** [getsentry/raven-csharp#281]
Noticed this when upgrading some packages today:

![](https://i.imgur.com/r1fYtiE.png)

Should we be moving away from SharpRaven to Sentry's package? I don't see anything in the documentation here about it.

**Comment by bruno-garcia** [comment]
We've added a note to the README:

<img width="795" alt="image" src="https://user-images.githubusercontent.com/1633368/70870205-9001a500-1f90-11ea-83e6-34b90c628ef1.png">

[Here's a bit of a background of the change, from Sentry's blog.](https://docs.sentry.io/development/sdk-dev/unified-api/)

I suggest looking at the docs now. [This is the general docs which IMHO is a must read](https://docs.sentry.io/error-reporting/quickstart/?platform=csharp).

[There's some more .NET specific docs you might want to check too.](https://docs.sentry.io/platforms/dotnet/)

I hope that helps.

**Comment by danbopes** [comment]
Tis a sad day :(

Sharp Raven has much better support with breadcrumbs, and more. I'm going to be continuing to use this, until it gets removed all together.

**Comment by bruno-garcia** [comment]
@danbopes SharpRaven will never be removed. And we're committed to fix bugs too although nothing was raised for over a year. We still receive millions of events from this SDK by thousands of customers but everyone is moving over to the [new Sentry SDK](https://github.com/getsentry/sentry-dotnet).

The new SDK also supports Breadcrumbs and much more.
When it was first released, version 1.0.0, the new `Sentry` SDK came with these features:

# First major release of the new .NET SDK.

## Main features

### Sentry package
* Automatic Captures global unhandled exceptions (AppDomain)
* Scope management
* Duplicate events automatically dropped
* Events from the same exception automatically dropped
* Web proxy support
* HttpClient/HttpClientHandler configuration callback
* Compress request body
* Event sampling opt-in
* Event flooding protection (429 retry-after and internal bound queue)
* Release automatically set (AssemblyInformationalVersionAttribute, AssemblyVersion or env var)
* DSN discovered via environment variable
* Release (version) reported automatically
* CLS Compliant
* Strong named
* BeforeSend and BeforeBreadcrumb callbacks
* Event and Exception processors
* SourceLink (including PDB in nuget package)
* Device OS info sent
* Device Runtime info sent
* Enable SDK debug mode (opt-in)
* Attach stack trace for captured messages (opt-in)

### Sentry.Extensions.Logging

* Includes all features from the `Sentry` package.
* BeginScope data added to Sentry scope, sent with events
* LogInformation or higher added as breadcrumb, sent with next events.
* LogError or higher automatically captures an event
* Minimal levels are configurable.

### Sentry.AspNetCore

* Includes all features from the `Sentry` package.
* Includes all features from the `Sentry.Extensions.Logging` package.
* Easy ASP.NET Core integration, single line: `UseSentry`.
* Captures unhandled exceptions in the middleware pipeline
* Captures exceptions handled by the framework `UseExceptionHandler` and Error page display.
* Any event sent will include relevant application log messages
* RequestId as tag
* URL as tag
* Environment is automatically set (`IHostingEnvironment`)
* Request payload can be captured if opt-in
* Support for EventProcessors registered with DI
* Support for ExceptionProcessors registered with DI
* Captures logs from the request (using Microsoft.Extensions.Logging)
* Supports configuration system (e.g: appsettings.json)
* Server OS info sent
* Server Runtime info sent
* Request headers sent
* Request body compressed

All packages are:
* Strong named
* Tested on Windows, Linux and macOS
* Tested on .NET Core, .NET Framework and Mono

[There are sample projects too.](https://github.com/getsentry/sentry-dotnet/tree/master/samples)


It's also very configurable, for example:

* HTTP Proxy
* Event sampling
* Enable request body extraction
* Send PII data (Personal Identifiable Information, requires opt-in)
* Read [diagnostics activity data]("https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md)
* BeforeSend: Callback to modify/reject event before sending
* BeforeBreadcrumb: Callback to modify/reject a breadcrumb
* LogEventFilter: Filter events by inspecting log data
* Maximum number of breadcrumbs to store
* Event queue depth
* Shutdown timeout: If there are events to send, how long to wait until shutdown
* Accept compressed response
* Compress request body
* Breadcrumb level: Minimum log level to store as a breadcrumb
* Event level: Minimum log level to send an event to Sentry
* Disable duplicate event detection
* Disable capture of global unhandled exceptions
* Add event processor
* Add exception processor
* Enable SDK debug mode
* Attach stack trace for captured messages (opt-in)

Over the past year we've made 28 more releases. Adding more features, etc.

I hope you decide to give it a try.

**Comment by sabiland** [comment]
> @danbopes SharpRaven will never be removed. 

Cool!
