### ISSUE TITLE
Consider using Ben.Demystifier for stack traces

### ISSUE THREAD

**Issue by scottt732** [getsentry/raven-csharp#282]
The stack traces reported by .NET -> Sentry are pretty cryptic, particularly when there are lambdas and/or async/await code.  It would be useful to either incorporate [benaadams/Ben.Demystifier](https://github.com/benaadams/Ben.Demystifier) into the client or allow users to plug in their own stack trace provider.

Additionally, it would be useful to format generic exception type names in a more friendly way.  Right now *SomeApplicationException<GenericParameterType>* would show up in Sentry as *SomeApplicationException`1*.  Something [like this](https://stackoverflow.com/a/33529925) would improve the situation a bit.

**Comment by bruno-garcia** [comment]
Please note `SharpRaven` is deprecated.

The new [Sentry SDK](https://www.nuget.org/packages/Sentry/) has [an extension for Ben.Demystifier](https://www.nuget.org/packages/Tuhu.Sentry.AsyncStackTrace/).
Besides that, I've raised an issue to perhaps bring this into the main SDK package:

https://github.com/getsentry/sentry-dotnet/issues/333
