### ISSUE TITLE
When sentry server is down , my app is slow down 

### ISSUE THREAD

**Issue by znsoft** [getsentry/raven-csharp#284]
### Environment

How do you use Sentry?
self-hosted

Which SDK and version?
JavaScript 5.11.1, .NET 1.2.0

### Steps to Reproduce

1. turn off Sentry server
2. start app used Sharpraven
3. mesure time

### Expected Result

good speed work.

### Actual Result

nothing good

**Comment by bruno-garcia** [comment]
This SDK is deprecated. Please use Sentry for .NET: https://github.com/getsentry/sentry-dotnet

That said, if you're using `Capture` with SharpRaven, it'll block the calling thread and attempt to send the event.
You could do a CaptureAsync without awaiting it, which has other gotchas.

The new Sentry SDK sends events in the background so does not suffer from this problem.
