### ISSUE TITLE
PCL Support for MonoTouch

### ISSUE THREAD

**Issue by thedillonb** [getsentry/raven-csharp#60]
I'd love to see PCL support for MonoTouch so I can use this in my iOS applications. I'd be happy to put the PR in if you're in agreement and don't already have that work underway.

**Comment by thedillonb** [comment]
Code is up. It's a lot so please ask questions. It's preliminary but it's got your PCL, Xamarin framework support, and 4.5 support. Silverlight, WPA, and other friends can be easily added.

**Comment by asbjornu** [comment]
Brilliant. I would love it if @mlb5000 or someone else with PCL needs could have a look at the code and see if what you've done works for them, @thedillonb. I'll have a look as soon as time allows, possibly early next week.

**Comment by mlb5000** [comment]
I will most likely try to just consume it before I read it :). I'll let you know if I have any problems integrating, which will be sometime this weekend since RayGun's reporting is just sad.

**Comment by mlb5000** [comment]
@thedillonb What is the best way to integrate this into my Xamarin.Android project that has a shared (portable) core library? I built the SharpRaven solution and imported the MonoAndroid10 DLL into the Android project, and the portable DLL into the portable library, but the app crashes soon after startup with a `System.TypeInitializationException`.

**Comment by mlb5000** [comment]
I have successfully sent an Info message to Sentry in my Xamarin.Android app

**Comment by thedillonb** [comment]
Hey @mlb5000, that's awesome. Any idea what caused the `TypeInitializationException`?

**Comment by mlb5000** [comment]
@thedillonb I was trying to log a message to Sentry from `MyApplication.OnCreate`, before any of my internal classes had been instantiated (somehow even the static ones). After I moved the Sentry call to somewhere else it was OK.

**Comment by mlb5000** [comment]
@thedillonb I have the following UnhandledExceptionHandler, but it doesn't look like the exception gets recorded to Sentry. Info messages get sent up, but not exceptions. Any ideas?

        private void MyApp_UnhandledExceptionHandler(object sender, RaiseThrowableEventArgs e)
        {
            _errorLogger.LogError(e.Exception);
            var message = string.Format(Message.ErrorInUi, e.Exception.Message);
            ShowToast(message);
        }

Maybe the app is terminating before the library gets a chance to log the error?

**Comment by mlb5000** [comment]
@thedillonb That is definitely what it is. I know raven-objc does something to load the iOS crash report when the app starts up. Is there some equivalent to this in Xamarin?

**Comment by ryanvalentin** [comment]
I haven't worked enough with Xamarin Android to know, but usually when the Unhandled Exception event is raised, you don't want to add anything to the UI like a toast. The app might be crashing prematurely because of that. You may also be able to avoid crashing by setting `e.Handled = true;`, and the app will remain open if the application state remains stable.

**Comment by thedillonb** [comment]
@mlb5000, so if you had an info message in your `UnhandledExceptionHandler` it was getting sent to Sentry but not if you sent an Exception? If that's the case it's pretty odd and I'll try to reproduce it on my side. Also, the are you `.Wait()` on the send task (Don't mark the event async, you must be synchronous here)? It's async so your app would exit the handler, and crash, even before it got the opportunity to send the message. If the event of sending to Sentry is non-deterministic then that would make sense to me. When `UnhandledExceptionHandler` gets called the App is pretty much on it's way out. I've never been successful trying to recover from that state. I'm pretty sure Xamarin's implementation is funky. Regardless, I've had success in the past taking the exception, serializing it to disc, and upon opening the app, check for it's presence, restore it and ship it off.

**Comment by mlb5000** [comment]
@thedillonb I've been using this for a little while and it has been working pretty well. Where would I look to update the bindings so that I can do things like identify users, set an app version, etc?

**Comment by GeirGrusom** [comment]
I need support for Profile24. Has there been any progress on PCL support?

**Comment by asbjornu** [comment]
@GeirGrusom Have a look at #65 and let me know if that fits the bill.

**Comment by asbjornu** [comment]
@GeirGrusom, @thedillonb, @mlb5000 and @ryanvalentin, could you please focus your energy on #70 or some derivate of it to move this feature request closer to completion? I have no need or knowledge of anything related to PCL, Xamarin or whatnot, so if you want this merged for a `2.0` release of SharpRaven, I really need your help.

**Comment by sbaechler** [comment]
Are there any updates on PCL support? There is a fork that does have PCL support but it also has a dependency on Xamarin.Forms which is not needed for native apps.

**Comment by asbjornu** [comment]
@sbaechler: Please have a look at what's going on in #189. If that direction is not solving your problems, I'm open to pull requests.
