### ISSUE TITLE
Make SharpRaven less System.Web hosting oriented

### ISSUE THREAD

**Issue by GeirGrusom** [getsentry/raven-csharp#71]
We are using Sentry for both server side and client side logging, but currently it is very much designed around System.Web from a hosting perspective.

It would be desirable to be able to specify username, device name and general request info both as client and specific request data rather than it always being automatically fetched.

Our use case is that we have servers servicing requests, which doesn't necessarily use System.Web but is instead a native code Mongoose web server. The .NET code is invoked as services running on that server, but there is no HttpContext available.

We also have client devices written using Xamarin, and they have a user id (which is the users authentication name), a device id (reported by the operating system) and a device name (given by the user in order to easily identify the device and where it belongs).

Currently we post this data as additional data, but this currently limits sentry's usefulness to us.

**Comment by asbjornu** [comment]
I completely agree and would welcome and merge any pull request that fixes the problem! :)

**Comment by asbjornu** [comment]
@GeirGrusom, could you please have a look at `develop` in its current state and see if it solves this better somehow? It will still try to load `System.Web.dll`, but its existence should be completely optional. There's also Nancy support in there now, so it shouldn't be difficult to add support for other platforms and environments.

**Comment by GeirGrusom** [comment]
Will do :)

**Comment by asbjornu** [comment]
Closing this in await for a new pull request.
