### ISSUE TITLE
Support fingerprint

### ISSUE THREAD

**Issue by dcramer** [getsentry/raven-csharp#72]
We just pushed out a release of Sentry today which adds this to basically replace hardcoding checksums in clients:

https://docs.getsentry.com/hosted/rollups/#custom-grouping

https://docs.getsentry.com/hosted/clientdev/attributes/

The gist is its an attribute on events that expects an array of strings as the value, or no value.

**Comment by asbjornu** [comment]
This would be so much easier to implement if you getsentry/sentry#1018 was completed. :wink:
