### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by dcramer** [getsentry/raven-csharp#79]
http://docs.travis-ci.com/user/languages/csharp/

**Comment by asbjornu** [comment]
This requires Mono support, which already fails in [TeamCity](http://teamcity.codebetter.com/viewType.html?buildTypeId=bt999), so I'm not sure what we can do to make this useful. And since we have a working TeamCity build (for Windows), what use will Travis have?

**Comment by dcramer** [comment]
Mostly that Travis is much more accessible to people than TeamCity. I still want to make this work but haven't had a chance yet. It sounds like it simple comes down to getting Mono support working (which tbh we want to do anyways) so I'll keep this open as a point of reference for now.

**Comment by asbjornu** [comment]
Sure. If you can find anyone with time and interest in fixing Mono compatibility, that would be great!
