### ISSUE TITLE
'exception' and/or 'timestamp' values are randomly being discarded in Sentry

### ISSUE THREAD

**Issue by mol** [getsentry/raven-csharp#82]
We've been using Raven and Sentry for a while now, and have always had an issue with exception data sometimes being unavailable in Sentry for no apparent reason. Testing it we've so far been able to reproduce it, and it seems to happen randomly or possibly only for certain users - but a huge lot of them.

Recentry, Sentry added a notification when it happens, so now when exception data is missing for an event I see:

>There were 2 errors encountered while processing this event.
>Discarded invalid value for parameter 'timestamp'
>Discarded invalid value for parameter 'exception'

Sometimes just for the 'exception' value, other times for both. Never for 'timestamp' alone I believe - but I would need to go through a lot of the events to check.

I've spoken with the Sentry team and they believe it's related to unicode characters somehow - but have so far been unable to spend more time looking into it.

Is there anything you guys can think of that could be causing this? My theory is it might be related to the obfuscation we're doing for the release version - which would explain why I can't reproduce it since my dev version isn't obfuscated.

**Comment by asbjornu** [comment]
@mol I contacted Sentry about the `timestamp` warning and got the following reply from @dcramer August 18:

> I think there was an open issue related to this possible. IIRC it's because of the microseconds value being longer than what Python supports by default, so we throw away the timestamp and use current time. Will get this fixed on our end.

The `exception` warning is new to me. Which version of [SharpRaven](https://www.nuget.org/packages/SharpRaven) are you using? Before [version 1.4.2](/getsentry/raven-csharp/releases/tag/1.4.2), there was a bug in how the `Modules` property was serialized.

**Comment by mol** [comment]
Thanks Asbjørn,

I see. The 'timestamp' isn't really important for us, so that's fine :)

The 'exception' is a problem though as it prevents us from viewing the stack trace and bundles tons of different issues together. We're using version 1.4.6 at the moment. I just updated to 1.5.0 on my dev machine though. I recall seeing that modules fix earlier and hoped it would fix it, but unfortunately it didn't :( I'm surprised we're the only one with the issue though. It happens with maybe 50% of the errors from users. We can't be the only ones using obfuscation? :)

@dcramer is the one that told me it's related to unicode characters, based on a quick test he did. I guess that could be a Python thing as well then. I'll run some tests where I try and throw the same error and stack trace as a failing one - obfuscated this time. I believe I tried it in the past where it wasn't obfuscated and it worked fine for me.

**Comment by asbjornu** [comment]
@mol If we get something working for #61, performing tests for integration issues like these would be much easier, so please feel free to pick that up and run with it. :wink: Otherwise, I'm not sure how we should test this, other than (as we do now) fire away at the live, public Sentry API and make assertions about the response.

I've never used obfuscation, but that indeed sounds like what might be causing the issue. The best way to get this solved would probably be to create a failing test in [Sentry](/getsentry/sentry) and pull request it.

**Comment by mol** [comment]
Yeah it's caused by the obfuscation. I just ran a version of my app that was rigged to fail both unobfuscated and obfuscated. The unobfuscated one didn't have the exception fail in Sentry and the obfuscated one did. Sentry has the raw JSON listed now so I have it for both reports. @dcramer how to proceed from here? I'm not really familiar with Python.

**Comment by asbjornu** [comment]
@dcramer Do you have an update on this? It seems related to getsentry/sentry#1508 and getsentry/sentry#2482. Do you think the details have been sufficiently captured in those issues so this can be closed? If so, @mol can perhaps follow those instead?

**Comment by dcramer** [comment]
I think its more than likely that if somethings being discarded its an encoding issue or its the wrong data type. I have a hard time keeping everything straight, but I know we've sorted out some timestamp issues in the past, so looking at specifically the exception value there's a good chance if its not consistently throwing it away its an encoding issue. Ignoring the linked issues as tbh both are old (and its hard to keep track if things are relevant if we didnt address them immediately), we have definitely dealt with some related things recently.

I have a strong point of view to close out issues if they're not updated, which to me suggests they're either irrelevant, or we simple didn't triage them. I'm not saying that in this case its irrelevant, but I believe that we can always re-open it if we're still seeing problems.

**Comment by mol** [comment]
We switched to another obfuscator that doesn't obfuscate the actual method and property names of the app, which means the stack trace wasn't obfuscated - that fixed the issue for us. Why there was an issue with the timestamp property I don't know though. Maybe it too was obfuscated somehow along with the app.

Anyway, as far as I'm concerned we can close the issue - but of course the underlying issue still exists. It's easily reproducable though. Just download the free trial of Crypto Obfuscator: http://www.ssware.com/cryptoobfuscator/obfuscator-net.htm and obfuscate a little sample app that forces an exception and sends it and its stack trace to Sentry. That should do it. Just make sure it's obfuscating method and property names at least.

**Comment by mol** [comment]
As I recall I saw errors when sending an unobfuscated stack trace through the data property though, at one time. But I fixed that by running a fork where I added a way to send a custom stack trace via the "regular channel" :)

**Comment by asbjornu** [comment]
@mol Perhaps you can replicate such an obfuscated stack trace in a test and PR that against the [Sentry](/getsentry/sentry) project? Either way, it's not much we can do about it in SharpRaven, so I'm closing this. Thanks for the input! :)

**Comment by mol** [comment]
You're welcome. I would, but I'm swamped with work, so I can't right now unfortunately - but maybe someone will see this and do it at some point :)
