### ISSUE TITLE
not working for windows phone?

### ISSUE THREAD

**Issue by Freundschaft** [getsentry/raven-csharp#84]
Am I mistaken or is this module not working for windows phone 8 and 8.1?

**Comment by asbjornu** [comment]
@Freundschaft I've never tried, but I guess this is related to #70.

**Comment by Freundschaft** [comment]
ah alright, I just tried to create a project as windows phone library, but it seems some namespaces are not present on windows phone that are used in raven-csharp. also I think it will be a lot harder to get the stacktrace with line numbers on windows phone because it's not possible to add PDB files to windows phone binaries :(

**Comment by asbjornu** [comment]
If line number isn't available, [SharpRaven will fallback to IL offset](/getsentry/raven-csharp/blob/master/src/app/SharpRaven/Data/ExceptionFrame.cs#L59). Not extremely useful, but it will at least not crash.

**Comment by Freundschaft** [comment]
there's something here but I havent tried it yet:
http://blogs.msdn.com/b/lucian/archive/2013/08/15/how-to-get-exception-stacktrace-line-numbers-on-windows-phone.aspx

**Comment by asbjornu** [comment]
@Freundschaft If you can get anything working, I'd appreciate a pull-request. :smiley:

**Comment by Freundschaft** [comment]
I will, as soon as I get something running, might take a while though cause I am busy in some other projects :)

**Comment by asbjornu** [comment]
@Freundschaft I'm closing this in wait for a PR. Hope you find time for it soon. :)
