### ISSUE TITLE
Exception Data is not send to Sentry by default

### ISSUE THREAD

**Issue by jmalczak** [getsentry/raven-csharp#86]
So i had to manually set Exception.Data property to be send as extra field. I believe it should be sent by default to sentry.

**Comment by dcramer** [comment]
Not a C# dev myself, can you explain what Exception.Data contains? I want to make sure we support use cases fairly upstream.

**Comment by jmalczak** [comment]
Sure. It's the same concept as extra field. This is taken from MSDN documentation "a collection of key/value pairs that provide additional user-defined information about the exception". You can read more about it here: https://msdn.microsoft.com/en-us/library/system.exception.data(v=vs.110).aspx

**Comment by asbjornu** [comment]
@jmalczak It's pretty easy to just shove the `Data` from the first exception in the stack inside the `extra` dictionary, but what about `Data` in `InnerException`s? Should each `Data` dictionary have their keys prefixed with the name of the exception they occurred in and then flattened to one dictionary? And how should this be combined with the existing `extra` dictionary? How should collisions in key names be handled?

A pull request tackling these issues would be highly appreciated. :)

**Comment by jmalczak** [comment]
Yeah if you think about inner exceptions it's not so trivial. Thx for the branch, I will take a look at it.

**Comment by jmalczak** [comment]
Ok. So i have removed this test from Integration and created new ones in JsonPacketFactory tests, i think it is fine to have it there since Capture is just wrapper for passing arguments. I have also fixed compilation error and issue with UniqueKeys. Please take a look, give me some feedback. Regarding data itself, maybe we can prefix exception data somehow, for example when you invoke Capture like that 
```
CaptureException(exception, extra: new { key = "value" }) and exception.Data = { { "key2", "value2 } }
```
maybe extra can look like this:
```javascript
{
 key: "value",
 exceptionEXCEPTIONTYPEData: { key2: "value2" },
 exceptionINNEREXCEPTIONTYPEData: {}
}
```
and so on. What do you think? It would be easy to distinct exception data and extra since if you don't know implementation (you don't know that you add extra first and exception data later) it's not easy to figure out if key comes from data or extra if they are the same.

Commit with changes: https://github.com/jmalczak/raven-csharp/commit/bf275fdcb4f7eca730cdd9032cfa45f8e5ae06c9

**Comment by asbjornu** [comment]
@jmalczak Thanks. I've merged and done a bit more on this. Let's continue the discussion in the #87. I'm closing this.
