### ISSUE TITLE
Move towards an Event Builder

### ISSUE THREAD

**Issue by dcramer** [getsentry/raven-csharp#94]
The current way that events are generated makes it tough to handle a lot of arbitrary attribute (due to C#'s lack of something like kwargs).

For example, every time a new arg is added, it gets added to CaptureException, and thus to JSONPacketFactory.Create.

It'd make sense to take the unique bits (exception) and split them into their own generative items, possibly something akin to:

```
event = BuildEvent()
event.tags = ...
client.Capture(event)
```

**Comment by asbjornu** [comment]
I agree that this would lead to cleaner extensibility. Adding an overload to `CaptureException`, or perhaps even an extension method, will preserve backwards compatibility too. :+1:

**Comment by asbjornu** [comment]
@dcramer I've created #98 that we can play around with until we reach a design we're happy with. I'm already quite happy with how it looks.
